### ISSUE TITLE
[Feature] Server Power Consumption

### ISSUE THREAD

**Issue by rud0812** [MauriceNino/dashdot#1030]
### Description of the feature

Would be cool to add power consumption in the OS widget. Also include an environment variable where we can input our avg $/kwh so we can get how much our server is costing us monthly/yearly.

**Comment by MauriceNino** [comment]
Hello there! Unfortunately, I don't think this is possible without some kind of measuring power socket on your machine. And then I probably would not be able to actually consume this data.

According to [this](https://unix.stackexchange.com/questions/10418/how-to-find-power-draw-in-watts) the only computers who actively track power consumption are notebooks.
