### ISSUE TITLE
[Bug]  Storage issue : No mount found

### ISSUE THREAD

**Issue by spl33f** [MauriceNino/dashdot#1033]
### Description of the bug

Hello,

I'm running dashdot in a container and I have an issue with the storage graph.

I'm using latest image.

    volumes:
      - /:/mnt/host:ro

![Capture d’écran 2024-01-26 104827](https://github.com/MauriceNino/dashdot/assets/101550996/3df22ec3-b166-49a7-82dc-888d23f14130)

root@SERVER:~# docker exec dashdot df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /
tmpfs                    65536         0     65536   0% /dev
tmpfs                  4046564         0   4046564   0% /sys/fs/cgroup
shm                      65536         0     65536   0% /dev/shm
/dev/md0               2385528   1553288    713456  69% /mnt/host
tmpfs                  4046564         0   4046564   0% /mnt/host/sys/fs/cgroup
devtmpfs               4042740         0   4042740   0% /mnt/host/proc/bus/usb
devtmpfs               4042740         0   4042740   0% /mnt/host/dev
tmpfs                  4046564       240   4046324   0% /mnt/host/dev/shm
tmpfs                1073741824         0 1073741824   0% /mnt/host/dev/virtualization
tmpfs                  4046564     19940   4026624   0% /mnt/host/run
tmpfs                   809316         0    809316   0% /mnt/host/run/user/196791
tmpfs                  4046564      2148   4044416   0% /mnt/host/tmp
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/docker/#snapshot
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/homes/#snapshot
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/SNAPSHOTS/#snapshot
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/surveillance/#snapshot
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/web/#snapshot
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/web_packages/#snapshot
/dev/loop0            15591832     57492  15415556   0% /mnt/host/volume1/@accountdb/@accountcache
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/@docker
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/@docker/btrfs
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /mnt/host/volume1/@docker/btrfs/subvolumes/8b3cd15c8f8e739167e6809e590f76e0126ed337c92851467851b8d8ff730661
tmpfs                    65536         0     65536   0% /mnt/host/volume1/@docker/btrfs/subvolumes/8b3cd15c8f8e739167e6809e590f76e0126ed337c92851467851b8d8ff730661/dev
shm                      65536         0     65536   0% /mnt/host/volume1/@docker/btrfs/subvolumes/8b3cd15c8f8e739167e6809e590f76e0126ed337c92851467851b8d8ff730661/dev/shmdf: /mnt/host/volume1/DESKTOP\040BACKUP/#snapshot: No such file or directory
df: /mnt/host/volume1/Microsoft\040OneDrive/#snapshot: No such file or directory
df: /mnt/host/volume1/SERVER\040BACKUP/#snapshot: No such file or directory
df: /mnt/host/volume1/SFTP\040Folder/#snapshot: No such file or directory
df: /mnt/host/volume1/Share\040Folder/#snapshot: No such file or directory
df: /mnt/host/volume1/Storage\040Reports/#snapshot: No such file or directory
df: /mnt/host/volume1/Sync\040DESKTOP\040DATA/#snapshot: No such file or directory

tmpfs                  4046564         0   4046564   0% /mnt/host/volume1/@docker/btrfs/subvolumes/8b3cd15c8f8e739167e6809e590f76e0126ed337c92851467851b8d8ff730661/sys/fs/cgroup
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /etc/resolv.conf
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /etc/hostname
/dev/mapper/cachedev_0
                     5621472524 2432349552 3189122972  43% /etc/hosts

Could you please help me to fix it ?

Thank you

### Info output of dashdot cli

```shell
root@SERVER:~# docker exec dashdot yarn cli info
INFO
=========
Yarn: 3.7.0
Node: v20.11.0
Dash: 5.8.3

Cwd: /app
Hash: f7ac2728b89a6c75502c9c736c46a94ff386889b
Platform: Linux dashdot 3.10.108 #69057 SMP Fri Jan 12 16:59:54 CST 2024 x86_64 Linux
Docker image: base
In Docker: true
In Docker (env): true
In Podman: false
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Where is your instance running?

Linux Server

### Additional context

Using Portainer within Container Manager on Synology NAS

**Comment by MauriceNino** [comment]
Hello there! Unfortunately, Synology is not a supported system and I can't help you with that problem, as I don't have a machine running it to get it working. There is a task already open for Synology (#938), so I will close this one for now. Please follow the other one to get updates on the progress.
