### ISSUE TITLE
[Feature] Show Percentages of each drive used

### ISSUE THREAD

**Issue by fidst** [MauriceNino/dashdot#104]
### Description of the feature

It would be cool to see the percentage used of each drive. Either by hovering or having a data point like the processor percentage.

This could also be shown by having a toggle like the processor for each core, but for each drive.

**Comment by fidst** [comment]
Right now you have a donut for both drives combined.

The total size and the size used is already known of the total space available.

In my case, 256.2GB is used. So the math would be
<img width="553" alt="image" src="https://user-images.githubusercontent.com/9792886/172658082-d8db5d36-e962-4c07-b4eb-da88661445e9.png">
(256.2/1141.1)*100 and round the decimals to 1 space.
22.5%

Then that percentage could be in the chart space, much like the ram or cpu
<img width="259" alt="image" src="https://user-images.githubusercontent.com/9792886/172658616-3a0996b2-ac24-457f-b4ff-d8b7db983e15.png">

**Comment by MauriceNino** [comment]
Ahh yeah got it! I don't know why I haven't added this yet, but I totally will.

**Comment by MauriceNino** [comment]
I will keep this issue open, because only the percentage has been added yet.

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 3.7.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/CHANGELOG.md) for more details.
