### ISSUE TITLE
Docker Swarm and Ceph support

### ISSUE THREAD

**Issue by belangerpascal** [MauriceNino/dashdot#1048]
### Description of the feature

Would love to see dashdot support swarm mode and capture and show data from all nodes in the swarm and also support ceph and show all data also.

**Comment by MauriceNino** [comment]
Hello, thanks for the suggestion, but unfortunately this is not within the scope of the project and would probably require an entire rewrite of most of the code. It would also be hard to show information of multiple nodes in such a limited space.
