### ISSUE TITLE
[Feature] Your discord invite does not work

### ISSUE THREAD

**Issue by thevrownguy** [MauriceNino/dashdot#1059]
### Description of the feature

New user and giving this a shot, but its bad when I cannot join the discord. I have it working, but your docuebntation is lacking in how you implenment all the options. Do you pass this in your compose file? I need it to ignore a GPU and only look at one, and thwere seems to be a feature for that, but its cryptic. How does someone reach a dev? Or maybe a community??

**Comment by MauriceNino** [comment]
The invite link still works for me <https://discord.gg/3teHFBNQ9W>.
