### ISSUE TITLE
[Bug] Quick question: How to configure environmental variables on Windows?

### ISSUE THREAD

**Issue by ChanLicher** [MauriceNino/dashdot#1069]
### Description of the bug

As the title described, I tried adding some environmental variables, but it did not work. Is there a file containing all the configurations?

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Desktop PC (Windows)

**Comment by MauriceNino** [comment]
Adding environment variables depend on your system. This type of question would maybe fit better on Discord, although I can't help you with that.
