### ISSUE TITLE
[Bug] Storage dont sowing used space and 

### ISSUE THREAD

**Issue by AlexRSA** [MauriceNino/dashdot#1074]
### Description of the bug
this is from the container
![imagen](https://github.com/user-attachments/assets/330ecf9a-40d9-4522-8740-2db2452c33a3)
![imagen](https://github.com/user-attachments/assets/45086eda-c917-43ec-b9c5-597fef67c10b)
![imagen](https://github.com/user-attachments/assets/dc23fdfb-0105-4542-9ff5-86fb59bb75d1)
and this is from host
![imagen](https://github.com/user-attachments/assets/8a2b74be-12de-499d-b980-f1ffa831e2d6)

### Where is your instance running?

Linux Server

**Comment by AlexRSA** [comment]
![imagen](https://github.com/user-attachments/assets/d34e358e-a05c-4d7a-ab41-488c9f46f04e)
Now i have the virtual working, How i can unattach the SSD to only show the virtual and do you know some method to change the name of the Volume

**Comment by MauriceNino** [comment]
To filter out drives you can use [`DASHDOT_FS_DEVICE_FILTER`](https://getdashdot.com/docs/configuration/storage#dashdot_fs_device_filter) and to rename drives you can use [`DASHDOT_OVERRIDE_STORAGE_BRANDS`](https://getdashdot.com/docs/configuration/storage#dashdot_override_storage_brands).

As I don't see any bug being described in the issue, I will close this for now. If you think that is a mistake, feel free to reopen and provide more information, please. Thank you!
