### ISSUE TITLE
[Bug] The dashdot homepage is not opening

### ISSUE THREAD

**Issue by mehmetaliadsan** [MauriceNino/dashdot#1075]
### Description of the bug

I am using ubuntu server 24.04. I installed the dashdot app through docker.

**my docker stack is below**

version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '1986:1986'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'

**Logs are below**

      'iso9660',
      'fuse.shfs',
      'autofs'
    ],
    fs_virtual_mounts: [],
    disable_integrations: false,
    show_dash_version: 'icon_hover',
    show_host: false,
    custom_host: undefined,
    page_title: 'dash.',
    use_imperial: false,
    network_speed_as_bytes: false,
    always_show_percentages: false,
    enable_cpu_temps: true,
    cpu_temps_mode: 'avg',
    widget_list: [ 'os', 'cpu', 'storage', 'ram', 'network' ],
    os_label_list: [ 'os', 'arch', 'up_since' ],
    cpu_label_list: [ 'brand', 'model', 'cores', 'threads', 'frequency' ],
    storage_label_list: [ 'brand', 'type', 'size', 'raid' ],
    ram_label_list: [ 'brand', 'type', 'size', 'frequency' ],
    network_label_list: [ 'type', 'speed_up', 'speed_down', 'interface_speed' ],
    gpu_label_list: [ 'brand', 'model', 'memory' ],
    os_widget_grow: 2.5,
    os_widget_min_width: 300,
    cpu_widget_grow: 4,
    cpu_widget_min_width: 500,
    cpu_shown_datapoints: 20,
    cpu_poll_interval: 1000,
    cpu_cores_toggle_mode: 'toggle',
    storage_widget_items_per_page: 3,
    storage_widget_grow: 3.5,
    storage_widget_min_width: 500,
    storage_poll_interval: 60000,
    ram_widget_grow: 4,
    ram_widget_min_width: 500,
    ram_shown_datapoints: 20,
    ram_poll_interval: 1000,
    speed_test_interval: 240,
    speed_test_interval_cron: undefined,
    network_widget_grow: 6,
    network_widget_min_width: 500,
    network_shown_datapoints: 20,
    network_poll_interval: 1000,
    gpu_widget_grow: 6,
    gpu_widget_min_width: 700,
    gpu_shown_datapoints: 20,
    gpu_poll_interval: 1000,
    override: {
      os: undefined,
      arch: undefined,
      cpu_brand: undefined,
      cpu_model: undefined,
      cpu_cores: undefined,
      cpu_threads: undefined,
      cpu_frequency: undefined,
      ram_brand: undefined,
      ram_size: undefined,
      ram_type: undefined,
      ram_frequency: undefined,
      network_type: undefined,
      network_speed_up: undefined,
      network_speed_down: undefined,
      network_interface_speed: undefined,
      network_public_ip: undefined,
      storage_brands: {},
      storage_sizes: {},
      storage_types: {},
      gpu_brands: [],
      gpu_models: [],
      gpu_memories: []
    }
  }
}
Running speed-test (this may take a few minutes)...
First measurement [Storage]: [ 22047776768 ]
First measurement [Network]: { up: 0, down: 0 }
First measurement [RAM]: 2240897024
First measurement [CPU]: [
  { load: 0.5408248626241458, temp: 40, core: 0 },
  { load: 0.3443505192709561, temp: 40, core: 1 },
  { load: 0.5680682813021949, temp: 70, core: 2 },
  { load: 0.1555470892162401, temp: 70, core: 3 },
  { load: 0.5784188652841615, temp: 41, core: 4 },
  { load: 0.09119956122169146, temp: 41, core: 5 },
  { load: 0.5485580098776616, temp: 41, core: 6 },
  { load: 0.07462896466374776, temp: 41, core: 7 },
  { load: 1.021111037125736, temp: 41, core: 8 },
  { load: 0.9790805431444047, temp: 41, core: 9 },
  { load: 0.7928737245099389, temp: 41, core: 10 },
  { load: 0.6485038010363287, temp: 41, core: 11 },
  { load: 0.7771291893704954, temp: 43, core: 12 },
  { load: 0.8014840544523887, temp: 43, core: 13 },
  { load: 0.7944483625463507, temp: 64, core: 14 },
  { load: 0.7857683652653052, temp: 48, core: 15 }
]
Speed-test completed successfully [speedtest-cli] {
  speedDown: 53657260.49058876,
  speedUp: 20413445.932366908,
  publicIp: undefined
}

when I enter the url on browser. the host is not working. what is the issue here?

<img width="865" alt="image" src="https://github.com/user-attachments/assets/26fa1745-d052-414c-a534-6bad7d9fbfc2">

### What browsers are you seeing the problem on?

Safari

### Where is your instance running?

Linux Server

**Comment by MauriceNino** [comment]
Doesn't seem like a bug to me, more like a configuration error.
The URL you entered is invalid too.

Firstly, you configured `1986:1986` for the port mappings, but the second port should be left untouched, because there is only a single service listening to the `3001` port inside the container. Please change this to `1986:3001` to make the service reachable from port `1986` in the outside network.

Secondly, your URL looks malformed. Make sure that IP is correct and remove the `www.` at the beginning.

If you have any more questions, I would suggest you joining the Discord server.

**Comment by svenjr** [comment]
I actually am having this same issue now. My docker compose file looks like this

```yaml
services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '80:3001'
    network_mode: "host"
    volumes:
      - /:/mnt/host:ro
      #- /home/sven/checkouts/svenjr/server-docker/dash/config:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_USE_IMPERIAL: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network,gpu'
      LOG_LEVEL: 'debug'
```

and when I loading `http://192.168.1.252:3001` I am getting an blank page. At one point, I did see a flash of a screen that looked like this 
![image](https://github.com/user-attachments/assets/fd16af55-4003-400d-bb9d-4ae833f4a17d)

My docker logs look the same as above as well

**Comment by prabhashithawe** [comment]
This happened to me too. If I remove `DASHDOT_ENABLE_CPU_TEMPS: 'true'`, everything works fine.
