### ISSUE TITLE
[Feature] Increasing the Update Speed of the Statistics

### ISSUE THREAD

**Issue by nordflow** [MauriceNino/dashdot#109]
### Description of the feature

I would like to increase the updating frequency of the statistics on the dashboard. If I'm not mistaken, it's around 1 second, which feels very choppy and slow.

**Comment by MauriceNino** [comment]
Hi there! Please have a look at the [configuration options](https://github.com/MauriceNino/dashdot/blob/main/CONFIGURATION.md), specifically everything that is called `*_POLL_INTERVAL`.

I would not recommend going very low, though, as it can be quite hard to run. If there is any way to animate graphs on the x-axis, I would be happy to make it smoother.
