### ISSUE TITLE
[Bug] OS release not showing correctly for Arch Linux

### ISSUE THREAD

**Issue by seriousm4x** [MauriceNino/dashdot#112]
### Description of the bug

My OS shows as `Arch Linux unknown` where it should be `Arch Linux rolling`.
When testing the output of systeminformation directly, platform shows as rolling. Seems like the release info is not read properly.

### How to reproduce

Just use arch btw, (No, honestly. I've tested it in a seperate vm and it also says unknown.)

### Relevant log output

```shell
dashdot log:

dashdot-dash-1  | 2022-06-12T08:30:17.573425224Z   os: {
dashdot-dash-1  | 2022-06-12T08:30:17.573429304Z     arch: 'x64',
dashdot-dash-1  | 2022-06-12T08:30:17.573433384Z     distro: 'Arch Linux',
dashdot-dash-1  | 2022-06-12T08:30:17.573436724Z     kernel: '5.18.3-arch1-1',
dashdot-dash-1  | 2022-06-12T08:30:17.573440004Z     platform: 'linux',
dashdot-dash-1  | 2022-06-12T08:30:17.573442834Z     release: 'unknown',
dashdot-dash-1  | 2022-06-12T08:30:17.573446084Z     uptime: 85800.52
dashdot-dash-1  | 2022-06-12T08:30:17.573449004Z   }

systeminformation output:

{
  platform: 'linux',
  distro: 'Arch',
  release: 'rolling',
  codename: '',
  kernel: '5.18.3-arch1-1',
  arch: 'x64',
  hostname: 'arch',
  fqdn: [Function: __node_internal_checkError] {
    [Symbol(Symbol.toPrimitive)]: [Function (anonymous)]
}
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Where is your instance running?

Desktop PC (Linux)

**Comment by MauriceNino** [comment]
Merged, thank you!

**Comment by seriousm4x** [comment]
Yes, its working. Thanks to both of you!

**Comment by MauriceNino** [comment]
Great, thanks to both of you as well! At first I thought someone opened a PR and Issue at once, because it was so fast lmao.
Took me a while to figure out that I am speaking to 2 people.
