### ISSUE TITLE
[Bug] error Command failed with signal "SIGINT".

### ISSUE THREAD

**Issue by thenamesjagger** [MauriceNino/dashdot#115]
### Description of the bug

I get this error on a raspberry pi 4 with ubuntu server 64bit. It comes after the speed test. It does not happen when building from source, only docker/docker-compose.

### How to reproduce

I just ran the docker command on the main github page ass is.

**Comment by MauriceNino** [comment]
Have you installed `speedtest-cli` or `speedtest` (from ookla)? Please run `which speedtest-cli` and `which speedtest` to make sure.

**Comment by MauriceNino** [comment]
Hey there, thanks for the issue. Can you please post the log output? Feel free to x out anything that is sensitive information.

**Comment by thenamesjagger** [comment]
I don't think the container gets fully created. There is no ID when I go to check. Here is what I get in the terminal:
![Screenshot from 2022-06-13 19-20-40](https://user-images.githubusercontent.com/67752390/173479831-87984443-53ad-4121-a797-8139c05dbdb0.png)

**Comment by MauriceNino** [comment]
Could it be that you want to run the docker container in the background? And are you using the command from the readme to run your dashdot instance?

Because it looks like you press `CTRL` + `C` while running the container. If you want to run your container in BG mode, please add the `-d` flag ([docs](https://docs.docker.com/engine/reference/run/#detached-vs-foreground))

**Comment by thenamesjagger** [comment]
Here is my docker log with it detached.

**Comment by MauriceNino** [comment]
Can't see any errors anymore, so I guess that works?

**Comment by thenamesjagger** [comment]
Any idea why the page doesn't load?

**Comment by thenamesjagger** [comment]
docker container run -d \
  --name dashdot \
  -p 80:3001 \
  -v /etc/os-release:/etc/os-release:ro \
  -v /proc/1/ns/net:/mnt/host_ns_net:ro \
  -v /media:/mnt/host_media:ro \
  -v /mnt:/mnt/host_mnt:ro \
  --privileged \
  mauricenino/dashdot

**Comment by MauriceNino** [comment]
What happens when you go to `localhost:80` in your browser? Are there any errors?
