### ISSUE TITLE
[Feature] Show multiple network interfaces

### ISSUE THREAD

**Issue by stavros-k** [MauriceNino/dashdot#117]
### Description of the feature

As far as I can tell, it only shows 1 interface currently.

I'd like to view more or at least an option to select which one to show.

As for now it defaults to my 10G NIC which is internal link with another server.

**Comment by MauriceNino** [comment]
Thanks for the request! I will add an option to select your desired interface.

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 3.4.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/CHANGELOG.md) for more details.
