### ISSUE TITLE
[Bug] Storage shows 100% used

### ISSUE THREAD

**Issue by Ic3Nine** [MauriceNino/dashdot#160]
https://pastebin.com/axeA8CTN - yarn output

compose config
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - 8086:3001
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS = true
      - DASHDOT_SHOW_HOST = true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW = true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES = true 
    volumes:
      - /etc/os-release:/etc/os-release:ro
      - /proc/1/ns/net:/mnt/host_ns_net:ro
      - /mnt:/mnt/host_mnt:ro
      - /media:/mnt/host_media:ro

I've tried removing the last two lines separately but it still doesn't work. Removing media, shows the bpool drive as free.  ADding it back shows it 100 used
https://i.imgur.com/Z4qNDeI.png

I only have 1 drive on the host and it's using zfs.

**Comment by Ic3Nine** [comment]
https://i.imgur.com/GT5k232.png
without those two volumes this is what  see

**Comment by MauriceNino** [comment]
🎉 This issue has been resolved in version 4.0.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/.github/CHANGELOG.md) for more details.
