### ISSUE TITLE
[Feature] Adding apps to dash

### ISSUE THREAD

**Issue by sheeepdev** [MauriceNino/dashdot#173]
### Description of the feature

Hey!

I discovered dashdot like 10 minutes ago and I'm loving it. Previously I was using [DashMachine](https://github.com/rmountjoy92/DashMachine) which I loved because I could customize the app entries. I found that dashdot doesn't really have any app type stuff and only monitors for system info, which I prefer but I miss adding links to my selfhosted apps (e.g Syncthing) on my server dashboard. This probably is not planned but it would be nice to have

*Btw, I tried searching around for a similar issue but found none, sorry if I missed something*

**Comment by MauriceNino** [comment]
Hey there! Thanks for the request - we are currently working on an [integration with Homarr](https://github.com/ajnart/homarr/issues/276). You can see how it will most likely look like here: https://github.com/ajnart/homarr/pull/277.

Would that be something that fits your needs?

Also, you can potentially integrate Dash. on any website you like, using [widgets](https://getdashdot.com/docs/integration/widgets).

But yes, you already said so - Dash. will never be a Personal Dashboard which holds links to your other apps. But it can be integrated with Personal Dashboards :)

**Comment by sheeepdev** [comment]
> But yes, you already said so - Dash. will never be a Personal Dashboard which holds links to your other apps. But it can be integrated with Personal Dashboards :)

Yeah, that was the answer I was searching for :)
Homarr seams promising but honestly it would be nicer to have everything in one.

Closing this one

**Comment by MauriceNino** [comment]
Yeah I get that, but unfortunately it would be worlds harder to do everything at once than to make multiple things that work well with each other. Hope you find something that suits your needs though.
