### ISSUE TITLE
[Bug] `/etc/os-release` is no longer needed

### ISSUE THREAD

**Issue by stavros-k** [MauriceNino/dashdot#181]
### Description of the bug

With the latest change where we mount `/` to `/mnt/host`, It's not needed to also mount `/etc/os-release`, as it already has access there.

### Relevant log output

```shell
For example mounting both `/` and `/etc/os-release` produces this:


Error: Command failed: ln -sf /mnt/host/etc/os-release /etc/os-release
ln: /etc/os-release: File exists
    at ChildProcess.exithandler (node:child_process:389:12)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:537:28)
    at Pipe.<anonymous> (node:net:747:14) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'ln -sf /mnt/host/etc/os-release /etc/os-release',
  stdout: '',
  stderr: 'ln: /etc/os-release: File exists\n'
}
```

**Comment by MauriceNino** [comment]
Hey there, thanks for the issue.

I think you are still using the mount `/etc/os-release:/etc/os-release:ro` right? In that case you would have to remove it, as with the new mount I do the mapping internally.

**Comment by stavros-k** [comment]
Yea, The issue was opened to remove the reference from the docs. 
( I removed the mount after I got the above error).

But checking again the reference is removed from docs, which probably means it was a caching issue from my browser (I was seeing an older version of the docs.).

Nothing to do :)

**Comment by MauriceNino** [comment]
Ahhh that makes sense.

No worries!

Actually, this issue actually made me notice another error: when running dash. from source, it would still attempt that volume mount, which is not necessary, or might even break things. Thank you for making me notice that indirectly haha
