### ISSUE TITLE
[Feature] Display system host name in the server widget

### ISSUE THREAD

**Issue by JesseWebDotCom** [MauriceNino/dashdot#189]
### Description of the feature

I'd like to be able to display the host machine name (with the "dash." removed). This allows people that do not have an FQDN or domain to have their system host name displayed.  I imagine the configuration option would be like the below:

**DASHDOT_SHOW_SYSTEM_HOST**

If you want to show the system host name in the server widget (e.g. my_server).

- type: boolean
- default: false

Note that this will only be shown when DASHDOT_SHOW_HOST=false

### Additional context

So for example, if I have a physical computer named "HAPPY" that runs docker and the dash container, DASHDOT_SHOW_SYSTEM_HOST=true would replace "dash." with "HAPPY"

**Comment by MauriceNino** [comment]
So, after some thinking about it, I decided that I will only implement the flag to change the page title. I see the name in the server widget as "branding" and removing that is not really something I want to do.

So in the next release there will be a new flag `DASHDOT_PAGE_TITLE` which can be set to any string value, that is then (after some loading delay) set as the page title.

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 4.3.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/.github/CHANGELOG.md) for more details.
