### ISSUE TITLE
Add automated multi-arch container build to Drone CI  workflow

### ISSUE THREAD

**Issue by Just5KY** [MauriceNino/dashdot#22]
https://raw.githubusercontent.com/xavier-hernandez/goaccess-for-nginxproxymanager/main/.github/workflows/docker-build.yml
https://raw.githubusercontent.com/Just5KY/honeypots/latest/.github/workflows/docker.yml

Pretty much all is there, you just need to cofigure it for your repo.
and add the secrets

![image](https://user-images.githubusercontent.com/71321862/164552986-e88ffbcc-6acb-49b7-90c0-675310c46a96.png)

**Comment by MauriceNino** [comment]
Thank you for the issue! I will try to map it to Drone CI to support the same features.

**Comment by MauriceNino** [comment]
I have finally gotten ARM builds to work now - would be great if you could test it out.

**Comment by Just5KY** [comment]
its working perfectly

**Comment by MauriceNino** [comment]
Very nice! Thank you.
