### ISSUE TITLE
[Bug] Diskstation 415+ doesn't show the right storage data 

### ISSUE THREAD

**Issue by Anarchon** [MauriceNino/dashdot#223]
### Description of the bug

I'm using a Synology Diskstation 415+ and my dashdot(docker) doesnt reports the right storage space

Install commands:
`docker run -d --name=dashdot \
-p 7512:3001 \
-e DASHDOT_ENABLE_CPU_TEMPS=true \
-e DASHDOT_DISABLE_TILT=true \
-e DASHDOT_DISABLE_HOST=true \
-e DASHDOT_OVERRIDE_OS=DSM \
-v /volume1/docker/dashdot/network:/mnt/host_ns_net:ro \
-v /volume1/docker/dashdot/media:/mnt/host_media:ro \
-v /volume1/docker/dashdot/host:/mnt/host_mnt:ro \
--privileged \
--restart always \
mauricenino/dashdot

`
![grafik](https://user-images.githubusercontent.com/6547561/180288705-829e1af0-76c0-44d3-b1ef-26dd8cd16e6a.png)

### Info output of dashdot cli

```shell
root@DiskStation:~# docker exec dashdot yarn cli info
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.6.0
Dash: 4.3.6

Cwd: /app
Hash: 7afc090092bc84b5572954cb54c43ab06ba9b523
In Docker: true
In Podman: false
In Docker (env): true
Done in 1.06s.
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Where is your instance running?

Other (Please specify below)

### Additional context

Synology Diskstation 415+ 
Ram :8GB
Harddrives: 4

**Comment by MauriceNino** [comment]
Hi, thanks for creating the issue. Unfortunately, the configuration you are using seems to be invalid. Please consult the docs to view how to install dashdot correctly here: https://getdashdot.com/docs/install/docker

Also, the options `DASHDOT_DISABLE_TILT` and `DASHDOT_DISABLE_HOST` are not needed anymore.
