### ISSUE TITLE
[Bug] not showing previews on hub.docker.com

### ISSUE THREAD

**Issue by 101br03k** [MauriceNino/dashdot#234]
### Description of the bug

while visiting the corrosponding page on the docker hub [(url)](https://hub.docker.com/r/mauricenino/dashdot) the previews where not loading. 

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Desktop PC (Linux)

**Comment by MauriceNino** [comment]
Thank you for letting me know! Changed the URLs, the images should now be visible again.
