### ISSUE TITLE
[Bug] Storage volumes are not displayed correctly

### ISSUE THREAD

**Issue by binuengoor** [MauriceNino/dashdot#252]
### Description of the bug

deployed in docker.

the disks are detected correctly but their free space is not displayed correctly.
![image](https://user-images.githubusercontent.com/62013964/183130864-6612621e-7721-4488-ab1c-5e20db3016c5.png)

### How to reproduce

docker compose volume mapping:
    volumes:
      - /etc/os-release:/etc/os-release:ro #to get os version
      - /:/mnt/host:ro

### Relevant log output

```shell
$ sudo docker exec dashdot df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay               24682964  14339080   9069228  61% /
tmpfs                    65536         0     65536   0% /dev
shm                      65536         0     65536   0% /dev/shm
/dev/mapper/pve-vm--100--disk--0
                      24682964  14339080   9069228  61% /etc/os-release
/dev/mapper/pve-vm--100--disk--0
                      24682964  14339080   9069228  61% /mnt/host
/dev/sdb1            960302804  78797128 881489292   8% /mnt/host/mnt/downloads
/dev/sdb1            960302804  78797128 881489292   8% /mnt/host/mnt/downloads
/dev/sde1            1921724676 248154736 1673553556  13% /mnt/host/mnt/movies
/dev/sde1            1921724676 248154736 1673553556  13% /mnt/host/mnt/bpMovies
/dev/sdd1            1921692964 1452915656 468658524  76% /mnt/host/mnt/tv
/dev/sdc1            960301168 411409588 548772796  43% /mnt/host/mnt/misc
/dev/sde1            1921724676 248154736 1673553556  13% /mnt/host/mnt/youtube
none                       492         4       488   1% /mnt/host/dev
udev                   3951812         0   3951812   0% /mnt/host/dev/net/tun
udev                   3951812         0   3951812   0% /mnt/host/dev/dri
udev                   3951812         0   3951812   0% /mnt/host/dev/full
udev                   3951812         0   3951812   0% /mnt/host/dev/null
udev                   3951812         0   3951812   0% /mnt/host/dev/random
udev                   3951812         0   3951812   0% /mnt/host/dev/tty
udev                   3951812         0   3951812   0% /mnt/host/dev/urandom
udev                   3951812         0   3951812   0% /mnt/host/dev/zero
tmpfs                  3986880         0   3986880   0% /mnt/host/dev/shm
none                       492         4       488   1% /mnt/host/proc/sys/kernel/random/boot_id
tmpfs                  1594756    157408   1437348  10% /mnt/host/run
tmpfs                     5120         0      5120   0% /mnt/host/run/lock
tmpfs                   797376         0    797376   0% /mnt/host/run/user/1000
/dev/mapper/pve-vm--100--disk--0
                      24682964  14339080   9069228  61% /mnt/host/var/lib/docker
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/a38a8a73b1dbb258dbfb8f2edcf0f4fcdd9ccb193ee026cae9c2fc8ecf5f9cf2/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/51a7f7e61536dfc2f2becaee010329bbe39f422728897dd57b04f3393e6b3c6e/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/41a8aa284033472928e237c3999b75f78b99268d8d51983288df478c9835cbe2/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/bcf8c0e5e519d24322b6fe29791ec9185aa6f5196b8e263dfba889c5f91c9b7c/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/d97fdc9ada9942af86f8b4aa8aa68e26fcc45e0a088112e245a2466d020fa5bf/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/543afbcbe8bd1db6e812a0374c044fa0212accd83082352269d7b5fc94a3065f/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/78a38ac6afddb2b03acb0dd8f66135b646d025159fd574d43ace9d401ab2700f/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/b05cf58c13dc2b5a66350dbdf63b237527db400ea65f762df8137a619672d747/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/c5415c97fee111217ab3ae13c531601c7bc875ae081c0011633968e92027d2a3/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/d2f18188bb972f20080a486c5ddb120d6704f26dd283c0ead77f6229cb56b7e6/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/6b56569bf69c30bd42341813bee6720ee8f6d5c223bdd563aafbddd2067fef9b/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/d72f12c660a76fcb1256c1703596902db165b15daf149c625e3a306f5e456821/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/534640ef2e404d2ee258f6e1321d829fe6928474c7715f409ceb155e9b3fd669/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/4eff9749b589d8c3417def8a5307eb1fa3dcc7de220b555bc27a029bee33e5b7/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/3c67b8c8c6d1355455c78c3e7814b9211cb08b3eb2e3c70ee2a2d031400d9831/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/5ea3ee93381893b35e89792be152c8dd6485132433ef97ba94a8bc65280a2567/merged
overlay               24682964  14339080   9069228  61% /mnt/host/var/lib/docker/overlay2/b108883a60b42ecfd0cf8dfad6e91c90242478c885372dc873fab2349a019e4e/merged
overlay               24682964  14339076   9069232  61% /mnt/host/var/lib/docker/overlay2/b108883a60b42ecfd0cf8dfad6e91c90242478c885372dc873fab2349a019e4e/merged
tmpfs                    65536         0     65536   0% /mnt/host/var/lib/docker/overlay2/b108883a60b42ecfd0cf8dfad6e91c90242478c885372dc873fab2349a019e4e/merged/dev
shm                      65536         0     65536   0% /mnt/host/var/lib/docker/overlay2/b108883a60b42ecfd0cf8dfad6e91c90242478c885372dc873fab2349a019e4e/merged/dev/shm
/dev/mapper/pve-vm--100--disk--0
                      24682964  14339076   9069232  61% /mnt/host/var/lib/docker/overlay2/b108883a60b42ecfd0cf8dfad6e91c90242478c885372dc873fab2349a019e4e/merged/etc/os-release
/dev/mapper/pve-vm--100--disk--0
                      24682964  14339076   9069232  61% /etc/resolv.conf
/dev/mapper/pve-vm--100--disk--0
                      24682964  14339076   9069232  61% /etc/hostname
/dev/mapper/pve-vm--100--disk--0
                      24682964  14339076   9069232  61% /etc/hosts
udev                   3951812         0   3951812   0% /dev/null
udev                   3951812         0   3951812   0% /dev/random
udev                   3951812         0   3951812   0% /dev/full
udev                   3951812         0   3951812   0% /dev/tty
udev                   3951812         0   3951812   0% /dev/zero
udev                   3951812         0   3951812   0% /dev/urandom
```

### Info output of dashdot cli

```shell
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.6.0
Dash: 4.3.6

Cwd: /app
Hash: 7afc090092bc84b5572954cb54c43ab06ba9b523
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.64s.
```

### What browsers are you seeing the problem on?

Chrome, Safari

### Where is your instance running?

Linux Server

### Additional context

docker running on a proxmox lxc container based on Debian 11.

**Comment by dawesry** [comment]
I believe I have the same a bug that is representing itself differently.

Runner Dash from Docker on Ubuntu. 

Dash is detecting the correct storage volume and size, but is saying 100% filled.

**Comment by MauriceNino** [comment]
Thanks for creating this issue. Can you please execute the following and paste the output, so that I can investigate what's creating the issue?

```
docker exec CONTAINER yarn cli raw-data --storage
```

@dawesry @binuengoor

**Comment by binuengoor** [comment]
Thanks.

yarn run v1.22.19
$ node dist/apps/cli/main.js raw-data --storage
Disk Layout: [
  {
    device: '/dev/sda',
    type: 'SSD',
    name: 'minisforum      ',
    vendor: 'ATA',
    size: 128035676160,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '61.3',
    serialNum: '',
    interfaceType: 'SATA',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sdb',
    type: 'HD',
    name: 'ASM1153E        ',
    vendor: 'Inateck',
    size: 1000204886016,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '0',
    serialNum: '',
    interfaceType: 'USB',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sdc',
    type: 'HD',
    name: 'Transcend       ',
    vendor: 'Transcend',
    size: 1000204886016,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '0',
    serialNum: '',
    interfaceType: 'USB',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sdd',
    type: 'HD',
    name: 'Elements 25A1   ',
    vendor: 'WD',
    size: 2000365289472,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '1012',
    serialNum: '',
    interfaceType: 'USB',
    smartStatus: 'unknown',
    temperature: null
  },
  {
    device: '/dev/sde',
    type: 'HD',
    name: 'BUP Slim BK     ',
    vendor: 'Seagate',
    size: 2000398933504,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '0304',
    serialNum: '',
    interfaceType: 'USB',
    smartStatus: 'unknown',
    temperature: null
  }
]
FS Size: [
  {
    fs: 'overlay',
    type: 'overlay',
    size: 25275355136,
    used: 17883865088,
    available: 6086242304,
    use: 74.61,
    mount: '/'
  },
  {
    fs: '/dev/mapper/pve-vm--100--disk--0',
    type: 'ext4',
    size: 25275355136,
    used: 17883865088,
    available: 6086242304,
    use: 74.61,
    mount: '/etc/os-release'
  },
  {
    fs: '/dev/sdb1',
    type: 'ext4',
    size: 983350071296,
    used: 80688259072,
    available: 902645035008,
    use: 8.21,
    mount: '/mnt/host/mnt/downloads'
  },
  {
    fs: '/dev/sde1',
    type: 'ext4',
    size: 1967846068224,
    used: 254110449664,
    available: 1713718841344,
    use: 12.91,
    mount: '/mnt/host/mnt/movies'
  },
  {
    fs: '/dev/sdd1',
    type: 'ext4',
    size: 1967813595136,
    used: 1487785631744,
    available: 479906328576,
    use: 75.61,
    mount: '/mnt/host/mnt/tv'
  },
  {
    fs: '/dev/sdc1',
    type: 'ext4',
    size: 983348396032,
    used: 421283418112,
    available: 561943343104,
    use: 42.85,
    mount: '/mnt/host/mnt/misc'
  }
]
Block Devices: [
  {
    name: 'sda',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 128035676160,
    physical: 'SSD',
    uuid: '',
    label: '',
    model: 'minisforum      ',
    serial: '',
    removable: false,
    protocol: 'sata',
    group: undefined
  },
  {
    name: 'sdb',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 1000204886016,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'ASM1153E        ',
    serial: '',
    removable: false,
    protocol: 'usb',
    group: undefined
  },
  {
    name: 'sdc',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 1000204886016,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'Transcend       ',
    serial: '',
    removable: false,
    protocol: 'usb',
    group: undefined
  },
  {
    name: 'sdd',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 2000365289472,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'Elements 25A1   ',
    serial: '',
    removable: false,
    protocol: 'usb',
    group: undefined
  },
  {
    name: 'sde',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 2000398933504,
    physical: 'HDD',
    uuid: '',
    label: '',
    model: 'BUP Slim BK     ',
    serial: '',
    removable: false,
    protocol: 'usb',
    group: undefined
  },
  {
    name: 'sda1',
    type: 'part',
    fsType: '',
    mount: '',
    size: 1031168,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'sda2',
    type: 'part',
    fsType: '',
    mount: '',
    size: 536870912,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'sda3',
    type: 'part',
    fsType: '',
    mount: '',
    size: 127497739776,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'sdb1',
    type: 'part',
    fsType: '',
    mount: '/mnt/host/mnt/downloads',
    size: 1000203820544,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'sdc1',
    type: 'part',
    fsType: '',
    mount: '/mnt/host/mnt/misc',
    size: 1000202142208,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'sdd1',
    type: 'part',
    fsType: '',
    mount: '/mnt/host/mnt/tv',
    size: 2000363289088,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'sde1',
    type: 'part',
    fsType: '',
    mount: '/mnt/host/mnt/youtube',
    size: 2000397868032,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  }
]
Done in 0.48s.

**Comment by dawesry** [comment]
```
yarn run v1.22.19
$ node dist/apps/cli/main.js raw-data --storage
Disk Layout: [
  {
    device: '/dev/mmcblk0',
    type: 'SSD',
    name: '',
    vendor: '',
    size: 31914983424,
    bytesPerSector: null,
    totalCylinders: null,
    totalHeads: null,
    totalSectors: null,
    totalTracks: null,
    tracksPerCylinder: null,
    sectorsPerTrack: null,
    firmwareRevision: '',
    serialNum: '0xa5780e76',
    interfaceType: '',
    smartStatus: 'unknown',
    temperature: null
  }
]
FS Size: [
  {
    fs: 'overlay',
    type: 'overlay',
    size: 31082250240,
    used: 17640722432,
    available: 12128518144,
    use: 59.26,
    mount: '/'
  },
  {
    fs: '/dev/mmcblk0p2',
    type: 'ext4',
    size: 31082250240,
    used: 17640722432,
    available: 12128518144,
    use: 59.26,
    mount: '/mnt/host'
  },
  {
    fs: '/dev/loop1',
    type: 'squashfs',
    size: 60686336,
    used: 60686336,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/core20/1585'
  },
  {
    fs: '/dev/loop2',
    type: 'squashfs',
    size: 51380224,
    used: 51380224,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/core18/2406'
  },
  {
    fs: '/dev/loop0',
    type: 'squashfs',
    size: 51511296,
    used: 51511296,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/core18/2542'
  },
  {
    fs: '/dev/loop3',
    type: 'squashfs',
    size: 106430464,
    used: 106430464,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/lxd/23274'
  },
  {
    fs: '/dev/loop4',
    type: 'squashfs',
    size: 42598400,
    used: 42598400,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/snapd/16019'
  },
  {
    fs: '/dev/loop7',
    type: 'squashfs',
    size: 42729472,
    used: 42729472,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/snapd/16299'
  },
  {
    fs: '/dev/loop5',
    type: 'squashfs',
    size: 60686336,
    used: 60686336,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/core20/1590'
  },
  {
    fs: '/dev/loop6',
    type: 'squashfs',
    size: 107085824,
    used: 107085824,
    available: 0,
    use: 100,
    mount: '/mnt/host/snap/lxd/23350'
  },
  {
    fs: '/dev/mmcblk0p1',
    type: 'vfat',
    size: 264289280,
    used: 161421312,
    available: 102867968,
    use: 61.08,
    mount: '/mnt/host/boot/firmware'
  },
  {
    fs: '192.168.1.25:/volume1/Media',
    type: 'nfs4',
    size: 9917050519552,
    used: 2033753522176,
    available: 7883175362560,
    use: 20.51,
    mount: '/mnt/host/mnt/Media'
  }
]
Block Devices: [
  {
    name: 'mmcblk0',
    type: 'disk',
    fsType: '',
    mount: '',
    size: 31914983424,
    physical: 'SSD',
    uuid: '',
    label: '',
    model: '',
    serial: '0xa5780e76',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop0',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/core18/2542',
    size: 51396608,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop1',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/core20/1585',
    size: 60669952,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop2',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/core18/2406',
    size: 51380224,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop3',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/lxd/23274',
    size: 106422272,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop4',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/snapd/16019',
    size: 42594304,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop5',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/core20/1590',
    size: 60669952,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop6',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/lxd/23350',
    size: 106983424,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'loop7',
    type: 'loop',
    fsType: 'squashfs',
    mount: '/mnt/host/snap/snapd/16299',
    size: 42602496,
    physical: '',
    uuid: '',
    label: '',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'mmcblk0p1',
    type: 'part',
    fsType: 'vfat',
    mount: '/mnt/host/boot/firmware',
    size: 268435456,
    physical: '',
    uuid: '2EC5-A982',
    label: 'system-boot',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  },
  {
    name: 'mmcblk0p2',
    type: 'part',
    fsType: 'ext4',
    mount: '/mnt/host',
    size: 31645482496,
    physical: '',
    uuid: 'c21fdada-1423-4a06-be66-0b9c02860d1d',
    label: 'writable',
    model: '',
    serial: '',
    removable: false,
    protocol: '',
    group: undefined
  }
]
Done in 2.05s.

```

**Comment by MauriceNino** [comment]
@binuengoor It seems like your drives are mounted multiple times in the same system. Can you tell me more about that? In your df output, there are multiple results for `/dev/sde1` - in the output of the command I sent you, there is then a mismatch between the sizes entry and the partition entry in the blocks.

```
{
  fs: '/dev/sde1',
  type: 'ext4',
  size: 1967846068224,
  used: 254110449664,
  available: 1713718841344,
  use: 12.91,
  mount: '/mnt/host/mnt/movies'
},
```

vs.

```
{
  name: 'sde1',
  type: 'part',
  mount: '/mnt/host/mnt/youtube',
  size: 2000397868032
  // ... (stripped away some unncessary content)
}
```

**Comment by MauriceNino** [comment]
@dawesry Your problem was that there was a network drive which was not caught by our filter. I have now added it, so the problem will be fixed in the next release (in 30 min).

```
{
  fs: '192.168.1.25:/volume1/Media',
  type: 'nfs4',
  size: 9917050519552,
  used: 2033753522176,
  available: 7883175362560,
  use: 20.51,
  mount: '/mnt/host/mnt/Media'
}
```

**Comment by binuengoor** [comment]
> @binuengoor It seems like your drives are mounted multiple times in the same system.

Yes. These are my usb drive mappings on proxmox lxc.
I added the subfolders as mountpoints for few docker apps.
Is there a way to ignore and see only unique drives in dashdot? @MauriceNino

**Comment by MauriceNino** [comment]
@binuengoor I think for your use-case it would be best to just manually mount the needed drives.

e.g.

```
volumes:
  - /etc/os-release:/mnt/host/etc/os-release:ro
  - /proc/1/ns/net:/mnt/host/proc/1/ns/net:ro
  - /mnt/downloads:/mnt/host/mnt/downloads:ro
  - /mnt/movies:/mnt/host/mnt/movies:ro
  - /mnt/tv:/mnt/host/mnt/tv:ro
  - /mnt/misc:/mnt/host/mnt/misc:ro
```

> Note: You need to remove the old mount `/:/mnt/host` to avoid double mounts

Lmk if that works

**Comment by binuengoor** [comment]
> @binuengoor I think for your use-case it would be best to just manually mount the needed drives.

Perfect! Thanks a lot. I didnt understand how these mounts work in the volume section. Much appreciated.

**Comment by MauriceNino** [comment]
No worries, glad it worked out for you! :)

**Comment by dawesry** [comment]
Fixed. Gorgeous, thank you!

> @dawesry Your problem was that there was a network drive which was not caught by our filter. I have now added it, so the problem will be fixed in the next release (in 30 min).
> 
> 
> 
> ```
> 
> {
> 
>   fs: '192.168.1.25:/volume1/Media',
> 
>   type: 'nfs4',
> 
>   size: 9917050519552,
> 
>   used: 2033753522176,
> 
>   available: 7883175362560,
> 
>   use: 20.51,
> 
>   mount: '/mnt/host/mnt/Media'
> 
> }
> 
> ```

**Comment by dawesry** [comment]
> @dawesry Your problem was that there was a network drive which was not caught by our filter. I have now added it, so the problem will be fixed in the next release (in 30 min).
> 
> 
> 
> ```
> 
> {
> 
>   fs: '192.168.1.25:/volume1/Media',
> 
>   type: 'nfs4',
> 
>   size: 9917050519552,
> 
>   used: 2033753522176,
> 
>   available: 7883175362560,
> 
>   use: 20.51,
> 
>   mount: '/mnt/host/mnt/Media'
> 
> }
> 
> ```

Just FYI this still doesn't display the mounted drive. I'm not sure if I have to set an volume variable, but when I add: 

```
-v /mnt/Media/:/mnt/host/mnt/Media:ro \

```

nothing changes.

**Comment by MauriceNino** [comment]
@dawesry Network drives can not be shown, as there is no physical information available. The newest version filters its size out, so that it doesn't contribute to the total size.

You can try using [`DASHDOT_FS_VIRTUAL_MOUNTS`](https://getdashdot.com/docs/config#dashdot_fs_virtual_mounts) with a value of `nfs4` to at least show it as a virtual mount in the split view.

**Comment by dawesry** [comment]
I appreciate it! I will try this and see what happens!

> @dawesry Network drives can not be shown, as there is no physical information available. The newest version filters its size out, so that it doesn't contribute to the total size.
> 
> 
> 
> You can try using [`DASHDOT_FS_VIRTUAL_MOUNTS`](https://getdashdot.com/docs/config#dashdot_fs_virtual_mounts) with a value of `nfs4` to at least show it as a virtual mount in the split view.
