### ISSUE TITLE
[Feature] drive naming

### ISSUE THREAD

**Issue by trackermb** [MauriceNino/dashdot#294]
### Description of the feature

ability to name the drives within config, As I have 2 drives which are the same size and model so its not clear which one is which.

**Comment by MauriceNino** [comment]
Hello, thanks for creating an issue.
You can use overrides in this case - specifically [`DASHDOT_OVERRIDE_STORAGE_BRANDS`](https://getdashdot.com/docs/config/overrides#dashdot_override_storage_brands).
