### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by dibu28** [MauriceNino/dashdot#327]
### Description of the feature

Please
1) add temperatures from `sensors` and `hddtemp`
for cpu, gpu and for each phisical disk.

2) and may be fan speed from sensors.

**Comment by MauriceNino** [comment]
Hey, thanks for creating a feature request!

CPU temperature can be read with the flag [dashdot_enable_cpu_temps](https://getdashdot.com/docs/config#dashdot_enable_cpu_temps). 

CPU fan speed can not be read currently ([systeminformation docs](https://systeminformation.io/cpu.html)), so if you want that added, I suggest adding a feature request to the repository of systeminformation.

Harddisk temperature is kind of hit or miss, if it can be read, but even if it was somewhat consistent - where would I even show it in the UI?

I don't think those requests are currently solvable, so I will close this issue for now. If something changes, I am happy to reopen it.
