### ISSUE TITLE
Design flaw with 4+ drives

### ISSUE THREAD

**Issue by Ahwxx** [MauriceNino/dashdot#33]
Hey there,

As I've noticed after setting up this dashboard, when I added 3 drives to my server, they showed up outside of the border of the 'panel'.

Here is a screenshot with the problem: [https://prnt.sc/g7vnwKuHeooq](https://prnt.sc/g7vnwKuHeooq).

I hope this problem can be fixed. As I don't know any solution, I didn't make a PR.

Also some other minor details are that the CPU threads show up as cores. On my 2700X it shows to have 16 cores whilst it has 8 cores with Hyperthreading/SMT.

Cheers!
- Ahwx

**Comment by MauriceNino** [comment]
Hello, thanks for creating an issue!

A few more questions about the problems you encountered:

1. The image looks like it is somehow showing in a weird size - do you use any zoom on your browser, or are you on a resolution, lower than 1080p?
2. About the CPU problem - can you maybe show me an image of what you mean? There should be two labels - one for threads and one for cores.

**Comment by MauriceNino** [comment]
After digging a little further into the CPU problem you mentioned, I can now see the problem you described and have created an issue on the relevant project sebhildebrandt/systeminformation#684. I will try to implement a hotfix, in case this takes a while to resolve.

**Comment by Ahwxx** [comment]
Hey,

I use 1920x1080 without any zoom. Windows 11's zoom is set to 100%.

As for the CPU 'problem', it seems like you've already fixed it (can't access my server right now), so I guess you don't need those anymore? If you do, you can see for yourself at [https://stats.jaapvd.nl](https://stats.jaapvd.nl).

**Comment by MauriceNino** [comment]
Yeah, the CPU problem should be fixed now, but it would still be really helpful to see if it works for your environment too & see if the fix for the drives works (It's more of a workaround, because I honestly don't know how else I would show it). It would be highly appreciated if you could update your deployment to the latest dev version.

**Comment by Ahwxx** [comment]
Alright I will try. I'm not really good with Docker, will the following do:

```
docker container run -it \
  -p 8099:3001 \
  --privileged \
  --env DASHDOT_OVERRIDE_DISTRO "Ubuntu" \
  --name dashdot \
  mauricenino/dashdot:dev
```

**Comment by MauriceNino** [comment]
Yes, that should work just fine, if you have not pulled any dev image before (which I am assuming you didn't).

**Comment by Ahwxx** [comment]
Sorry for the late reply, as you can see [here](https://stats.jaapvd.nl/), the core count and drives issues are fixed. Now the memory brand and speed are no longer showing up...

**Comment by MauriceNino** [comment]
Thank you. Could you paste the content of the log please?

**Comment by Ahwxx** [comment]
```
yarn run v1.22.18


$ (cd ./backend && yarn start)


$ node .


listening on *:3001


Static Server Info: {


  os: {


    arch: 'x64',


    distro: 'Alpine Linux',


    kernel: '5.4.0-109-generic',


    platform: 'linux',


    release: '3.15.4',


    uptime: 549050.29


  },


  cpu: {


    brand: 'AMD',


    model: 'Ryzen 7 2700X',


    cores: 8,


    threads: 16,


    frequency: 3.7


  },


  ram: {


    size: 25199984640,


    layout: [ { brand: undefined, type: '', frequency: 0 } ]


  },


```

**Comment by MauriceNino** [comment]
Are you sure that you ran it with the --privileged flag? There has been no change in the backend for the RAM part afaik.
