### ISSUE TITLE
Blank page - Cannot read properties of undefined (reading 'brand')

### ISSUE THREAD

**Issue by heyiamsven** [MauriceNino/dashdot#35]
Hey,

I'm trying to run dashdot with docker on my Odroid N2+ running Armbian. I've tried this command:
> docker container run -it \
>   -p 80:3001 \
>   --privileged \
>   --name dashdot \
>   mauricenino/dashdot

However if I visit the dashdot overview page it's in a completely blank state. If I inspect the webpage it spits out those errors:

> TypeError: Cannot read properties of undefined (reading 'brand')
>     at Qn (storage.tsx:45:64)
>     at ia (react-dom.production.min.js:157:137)
>     at Vc (react-dom.production.min.js:267:460)
>     at zu (react-dom.production.min.js:250:347)
>     at ju (react-dom.production.min.js:250:278)
>     at ku (react-dom.production.min.js:250:138)
>     at mu (react-dom.production.min.js:243:163)
>     at react-dom.production.min.js:123:115
>     at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
>     at qi (react-dom.production.min.js:122:325)
> cc @ react-dom.production.min.js:216
> DevTools failed to load source map: Could not load content for chrome-extension://dndehlekllfkaijdlokmmicgnlanfjbi/common/lib/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

Log (from executing docker run):

> yarn run v1.22.18
> $ (cd ./backend && yarn start)
> $ node .
> listening on *:3001
> Static Server Info: {
>   os: {
>     arch: 'arm64',
>     distro: 'Alpine Linux',
>     kernel: '5.10.103-meson64',
>     platform: 'linux',
>     release: '3.15.4',
>     uptime: 97630.84
>   },
>   cpu: {
>     brand: 'Cortex-A53',
>     model: '',
>     cores: 6,
>     threads: 6,
>     frequency: 2.27
>   },
>   ram: {
>     size: 3967762432,
>     layout: [ { brand: undefined, type: '', frequency: 0 } ]
>   },
>   storage: { layout: [] },
>   config: {
>     port: 3001,
>     disable_tilt: false,
>     disable_host: false,
>     os_widget_enable: true,
>     os_widget_grow: 1,
>     cpu_widget_enable: true,
>     cpu_widget_grow: 2,
>     cpu_shown_datapoints: 20,
>     cpu_poll_interval: 1000,
>     ram_widget_enable: true,
>     ram_widget_grow: 1.5,
>     ram_shown_datapoints: 20,
>     ram_poll_interval: 1000,
>     storage_widget_enable: true,
>     storage_widget_grow: 1.5,
>     storage_poll_interval: 60000,
>     override: {
>       os: undefined,
>       arch: undefined,
>       cpu_brand: undefined,
>       cpu_model: undefined,
>       cpu_cores: undefined,
>       cpu_threads: undefined,
>       cpu_frequency: undefined,
>       ram_brand: undefined,
>       ram_size: undefined,
>       ram_type: undefined,
>       ram_frequency: undefined,
>       storage_brand_1: undefined,
>       storage_size_1: undefined,
>       storage_type_1: undefined,
>       storage_brand_2: undefined,
>       storage_size_2: undefined,
>       storage_type_2: undefined,
>       storage_brand_3: undefined,
>       storage_size_3: undefined,
>       storage_type_3: undefined,
>       storage_brand_4: undefined,
>       storage_size_4: undefined,
>       storage_type_4: undefined,
>       storage_brand_5: undefined,
>       storage_size_5: undefined,
>       storage_type_5: undefined
>     }
>   }
> }
> 

It would be great if you could explain me what I'm doing wrong, for me it looks like that the variable 'brand' is empty and causing errors. 

I'm also very new to docker and I would like to know if there is any *.env-config file I can edit + how I can configure dashdot to automatically start after system boot.

**Comment by MauriceNino** [comment]
Hey this is a bug that currently exists on the main release, but is already fixed on the dev branch. I will release a new version right now. Could you pull this image and test it again?

**Comment by MauriceNino** [comment]
Newest image is now on DockerHub. Could you pull & redeploy? `docker image pull mauricenino/dashdot:latest`

Also for your other questions:

- To read more about environment variables and configuration, please have a look at the README (https://github.com/MauriceNino/dashdot#Configuration-Options)
- If you are running docker on linux, you just need to add a restart policy I think (https://docs.docker.com/config/containers/start-containers-automatically/) to start it on boot

**Comment by heyiamsven** [comment]
Hello,
thankyou for the quick update. I pulled the newest image and redeployed it. Everything is working now fine!
