### ISSUE TITLE
[Feature] Add Docker container dashboards

### ISSUE THREAD

**Issue by Eirikr70** [MauriceNino/dashdot#361]
### Description of the feature

Just proposing, I don't know to which extent this is feasible. Since many selfhosters use Docker, I think it would be valuable to have a dashboard indicating the resource consumption of every running container. That might allow users to check whether the consumption is acceptable in regard to the value of the app.

### Additional context

That might be achieved through gathering data such as docker stats.

**Comment by MauriceNino** [comment]
Hey there, unfortunately, this is not planned as it does not fit the project scope. I recommend using Homarr, which integrates with dashdot and also has a docker integration.

Duplicate of #42.
