### ISSUE TITLE
[Feature] Add Disk % Used to UI (without hovering)

### ISSUE THREAD

**Issue by lhoggatt17** [MauriceNino/dashdot#370]
### Description of the feature

It would be cool if we could embed the % of disk used into the plots:
![image](https://user-images.githubusercontent.com/37279082/189800644-e966dec1-c21f-4ed3-9b80-f3d87811499b.png)

Then we wouldn't have to hover over the element. It would also make viewing the dashboard on a mobile device easier. You could make this the default behavior for the `DASHDOT_ALWAYS_SHOW_PERCENTAGES = true` option. If there was less than x% disk, you'd have to have it on the grey side. Otherwise, it would be nice to have it inside the green bar.

**Comment by MauriceNino** [comment]
Hey, thanks for creating this issue. This sounds like a really great idea in theory, but I am having some issues with it:

- The bars are responsive and change their size with the amount of drives as well as the amount of space available (display size). How would I make sure that the font is always viewable, centered and looks nice?
- If there are some percentages on the green side and some on the gray side, it would look a bit inconsistent. But if I put them all on the left, they might overlap the border between green and gray + they might be completely on the gray side. This might not look too bad, though, so I think it could be a non-issue.

**Comment by lhoggatt17** [comment]
- this is a good question. I suppose you could just turn the %s off when there are too many drives. You could also add a scroll bar here if this setting is enabled. Or just keep scaling the text smaller: even if it's too small to read, it's still there. 
- Very true, I guess having them overlap wouldn't be the end of the world. Personally, I think having the % information is worth it since the difference between 80% and 90% might be hard to tell visually, but the numbers help make decisions like "it's time to buy a bigger drive" or whatever. I know people have all these fancy systems to monitor this stuff, but a beautiful, yet simple dashboard is more than enough for a simple home server with a few drives.

**Comment by MauriceNino** [comment]
Maybe I will make the bars limit to 3 per page (same as drives) and change them as well when the drives go to the next page. That would make sure there is enough space for this.

I will try this out, but currently it is a bit lower on my priority list (lots of bug-reports).

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 4.5.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/.github/CHANGELOG.md) for more details.
