### ISSUE TITLE
[Feature] Display hostname

### ISSUE THREAD

**Issue by sven-eliasen** [MauriceNino/dashdot#372]
### Description of the feature

It would be great to print the hostname of the machine next to the server information.
I've installed this great dashboard on two servers on mine but I when I set the browser in fullscreen I can't see which is which.

Current :  
![image](https://user-images.githubusercontent.com/37241392/189935505-3e416477-3dc6-4407-9c29-1405b4644e04.png)

Expectation : 
![image](https://user-images.githubusercontent.com/37241392/189938480-237c9ee0-6355-40a6-82ed-94a31bbb39f1.png)

I guess you would like to keep the "dash." but I really can't think of a better place.

**Comment by MauriceNino** [comment]
Hey there, thanks for opening an issue! Sounds like what you need is already possible with the flag [`DASHDOT_SHOW_HOST`](https://getdashdot.com/docs/config#dashdot_show_host). If this is not the case, please let me know.
