### ISSUE TITLE
[Feature] Name/brand for fs virtual mount

### ISSUE THREAD

**Issue by BunnySweety** [MauriceNino/dashdot#384]
### Description of the bug

It is not possible to assign a name or a brand to a virtual mount fs, to have a match in the display as for the other disks.

![image](https://user-images.githubusercontent.com/111603921/190872261-dfa0fa5d-59f9-45f7-8a27-17222ff35924.png)

### How to reproduce

Add this environment variable to the container: `DASHDOT_FS_VIRTUAL_MOUNTS=IP:/mount_point`

**Comment by donsizzla93** [comment]
> ### Description of the bug
> 
> It is not possible to assign a name or a brand to a virtual mount fs, to have a match in the display as for the other disks.
> 
> ![image](https://user-images.githubusercontent.com/111603921/190872261-dfa0fa5d-59f9-45f7-8a27-17222ff35924.png)
> 
> 
> ### How to reproduce
> 
> Add this environment variable to the container: `DASHDOT_FS_VIRTUAL_MOUNTS=IP:/mount_point`

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 4.5.5

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/.github/CHANGELOG.md) for more details.
