### ISSUE TITLE
[Bug] storage widget blank when multi-view set to true

### ISSUE THREAD

**Issue by dgrzjohn** [MauriceNino/dashdot#385]
### Description of the bug

Since 4.50 the storage widget is blank when multi-view is enabled.  You can see this on the widget creator, even the demo widget is blank when multi-view is set to true:
https://getdashdot.com/docs/integration/widgets

**Comment by MauriceNino** [comment]
Thanks for this issue - it will be fixed in the next release.

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 4.5.1

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/.github/CHANGELOG.md) for more details.
