### ISSUE TITLE
[Bug] speedtest-cli fail to connect to server

### ISSUE THREAD

**Issue by Zareix** [MauriceNino/dashdot#389]
### Description of the bug

Speedtest won't work and crash with error "ERROR: Unable to connect to servers to test latency."

I ran the command manually in the container and same error. Thought I ran the command ```speedtest -f json```and this one did worked providing following result :
```json
{
    "type": "result",
    "timestamp": "xxxx",
    "ping": {
        "jitter": 0.012999999999999999,
        "latency": 1.9550000000000001
    },
    "download": {
        "bandwidth": 11848976,
        "bytes": 46276160,
        "elapsed": 3911
    },
    "upload": {
        "bandwidth": 11851793,
        "bytes": 42839320,
        "elapsed": 3614
    },
    "packetLoss": 0,
    "isp": "SFR",
    "interface": {
        "internalIp": "xxxx",
        "name": "eth0",
        "macAddr": "xxxx",
        "isVpn": false,
        "externalIp": "xxxx"
    },
    "server": {
        "id": 123,
        "host": "speedtest.mire.sfr.net",
        "port": 8080,
        "name": "SFR",
        "location": "xxxx",
        "country": "France",
        "ip": "XXXX"
    },
    "result": {
        "id": "XXXX",
        "url": "https://www.speedtest.net/result/c/xxxx",
        "persisted": true
    }
}
```

### Relevant log output

```shell
Error: Command failed: speedtest-cli --json
ERROR: Unable to connect to servers to test latency.
    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'speedtest-cli --json',
  stdout: '',
  stderr: 'ERROR: Unable to connect to servers to test latency.\n'
}
```

### Info output of dashdot cli

```shell
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.9.0
Dash: 4.5.2

Cwd: /app
Hash: afb66c4801e68076ad4562ba67636f05120f9e9a
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.44s.
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Where is your instance running?

Linux Server

**Comment by MauriceNino** [comment]
Hey there, thanks for creating an issue. There are a few things that might be the cause of this:

- If you restart the container too often, your host's IP address might be flagged for spam - in that case, try again after some time
- Your docker container networking might have a problem (have you tried pinging google from inside?)

Can you make sure that none of those are the problem?

**Comment by Zareix** [comment]
- Don't think I'm flagged as spam, since the normal "soeedtest" cmd works
- Yes I can ping other websites

**Comment by Zareix** [comment]
Fixed by setting following env variable:
- DASHDOT_ACCEPT_OOKLA_EULA=true
