### ISSUE TITLE
[Feature] Network Graph

### ISSUE THREAD

**Issue by simonl169** [MauriceNino/dashdot#39]
Nice feature would be a netgraph, showing the incoming and outcoming amount of traffic

**Comment by MauriceNino** [comment]
Totally thought about that as well. I am definitely going to add it, but I am not sure where.

The thing is, I always wanted to make dashdot viewable without a scrollbar on a Full HD monitor in full screen. And with that given, it would look too crammed with 2 extra graphs (one for up & one for down). I will still add it as an opt-in feature for now, and add configuration options, to let everyone decide position & sizes of widgets.

If you have any ideas for positioning and/or size changes, please let me know!

**Comment by simonl169** [comment]
If you combine it, it would just be one graph

**Comment by MauriceNino** [comment]
That would be hard to read I think.

**Comment by jeryd** [comment]
unraid has a good way to show it... check it out

**Comment by jeryd** [comment]
![Screenshot 2022-05-25 042915](https://user-images.githubusercontent.com/4661200/170252202-a860bf5e-da70-4e2f-8546-b56fa7b042ed.png)

**Comment by MauriceNino** [comment]
That's exactly the problem - outbound will of the time be slower than inbound. I think I will stick to two smaller graphs instead of one big.

**Comment by MauriceNino** [comment]
![Screenshot from 2022-05-25 15-31-43](https://user-images.githubusercontent.com/18658092/170274313-66ad731b-283e-4426-8f4c-9bef1c88a889.png)

This is the current version of how it might look with the network chart. What do you think?

**Comment by jeryd** [comment]
I like it. You see how in the memory section you have a gradual fill? (red to black) Maybe something like that would work for the speed as well. Is there a way to identify what bar is down and what is up? (Without text - just by looking).

**Comment by MauriceNino** [comment]
The gradual fill will only appear when the stats are a bit higher.

This is pretty much how it will look:

![Screenshot from 2022-05-25 22-55-14](https://user-images.githubusercontent.com/18658092/170365640-e85c1d3a-4ddc-4e93-9df3-f057c828ebd1.png)

**Comment by MauriceNino** [comment]
Network Graph is now released in version 2.0.0! Please check out the new docs to see what you need to do to your installments to use the new features!

**Comment by simonl169** [comment]
that was fast, thank you!
