### ISSUE TITLE
Add the ability to manage multiple servers from a single place

### ISSUE THREAD

**Issue by SmartPhoneLover** [MauriceNino/dashdot#41]
**Is your feature request related to a problem? Please describe.**
Currently, you can only view the stats of the current server where the service (docker in my case) is installed and running.

**Describe the solution you'd like**
I think that allowing to manage the stats of more thatn a single server, from a single instance, would be a huge improvement.
These are my ideas:
A. Allow to register other Dash. instances inside the current one. So, you can jump from one server to the other.
B. Create a separate service to allow managing different Dash. instances, all from a single place. 

I think, the 'B' would be better, as you will only need to install only one copy. Then you add the rest of the Dash. running services inside it. Like, a Dashboard to manage and view other Dashboards.
Also, it would show a reduced version of every running Dash. instance, I mean, only showing very basic information from every server, so you can click on them to access every full Dash. dashboard.     

Maybe calling them as:
- Dashdot (server stats)
- Dashdot Central (manage and view all Dashdot instances)

Thank you.

**Comment by MauriceNino** [comment]
Maybe you could use another personal dashboard service to link to your instances of dash.? I don't know how a separate service to manage multiple dash. instances would look like.
