### ISSUE TITLE
[Bug] empty white page

### ISSUE THREAD

**Issue by xsolinsx** [MauriceNino/dashdot#410]
### Description of the bug

Hello, the webpage loads a white background and nothing else.
I have tried with firefox and edge and obtained the same result, also in private/incognito mode.
Sometimes the real background of dash. seems to get loaded as well as some widgets, but then it all gets overwritten by a white page.
The source says that I need to enable javascript but I don't think that's the problem, I can load each and every page in the web without any issue, so I think it is already enabled.
I have tried every version from 3.9.7 to the latest one

### How to reproduce

start an instance with 
DASHDOT_WIDGET_LIST: os,cpu,storage,ram,network,gpu

### Relevant log output

```shell
logs do not show anything about this
```

### Info output of dashdot cli

```shell
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.9.0
Dash: 4.5.2

Cwd: /app
Hash: afb66c4801e68076ad4562ba67636f05120f9e9a
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.29s.
```

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Where is your instance running?

Linux Server

### Additional context

without the gpu widget everything works correctly
I have an NVIDIA GTX970

**Comment by TotalChaos05** [comment]
Have you tried to use a chromium based browser? Thats what I tried using and it fixed it.

**Comment by MauriceNino** [comment]
Hello there, sorry for the late answer. You are running in a docker container, which does not officially support GPU for now. You can try running from host, or start with the guide [here](https://getdashdot.com/docs/config/widget-specific/graphics) to get started with running inside docker.
