### ISSUE TITLE
[Docs] Add Speed Test to Configuration Options

### ISSUE THREAD

**Issue by Gameniti** [MauriceNino/dashdot#412]
### Description of the feature

Hi,

I just found dash. and set it up on a company (test)server. Before that, I read somewhere something about the speedtest interval and wanted to configure it higher but didn't find that in the "Configuration Options" in the documentation where I expected it to be. 
After a quick google search I found a github issue that had the problem with too many speedtests and how to configure that.

I didn't expect a setting like this to be in the "Widget Options". IMO it would be better to put the Speedtest interval in the Configurations options -> general -> either above or under the "DASHDOT_ACCEPT_OOKLA_EULA".

Also the info on how much data a speedtest uses (even just approximately) would be helpful.

**Comment by MauriceNino** [comment]
Hi, thanks for creating this issue. The widget options are generally meant to couple similar options - namely intervals, labels, cache size. Therefore, I feel like it is logical to put an option for intervals in there as well.

About the needed data for a speedtest, I recommend looking it up on Ookla's tool site, as I only use their tool. I can not give any estimates, as I don't know what they are doing exactly. It's probably best if you just try it out. There is however a warning on the installation page, which warns users about data usage: https://getdashdot.com/docs/install.
