### ISSUE TITLE
[Bug] Cant get environemtal variables working

### ISSUE THREAD

**Issue by Gameniti** [MauriceNino/dashdot#414]
### Description of the bug

I try to add environmental variables but not all of them work.
I added the following to my docker run command:   

--env DASHDOT_SHOW_HOST='true' \
  --env DASHDOT_ENABLE_CPU_TEMPS='true' \
  --env DASHDOT_ENABLE_STORAGE_SPLIT_VIEW='true' \
  --env DASHDOT_PAGE_TITLE='dash. | local' \
  --env DASHDOT_SPEED_TEST_INTERVAL='43800' \

and Portainer pics them up so it seems that they are all set.
The problem is some (STORAGE_SPLIT_VIEW is one of them) aren't working. The storage icon is still a pie chart. While others (like PAGE_TITLE and CPU_TEMPS (only when not in "all cores" view?)) are working.

### How to reproduce

docker container run -it \
  -d \
  --env DASHDOT_SHOW_HOST='true' \
  --env DASHDOT_ENABLE_CPU_TEMPS='true' \
  --env DASHDOT_ENABLE_STORAGE_SPLIT_VIEW='true' \
  --env DASHDOT_PAGE_TITLE='dash. | local' \
  --env DASHDOT_SPEED_TEST_INTERVAL='43800' \
  -p 81:3001 \
  --name dashdot \
  --privileged \
  -v /:/mnt/host:ro \
  mauricenino/dashdot:latest

### Info output of dashdot cli

```shell
yarn run v1.22.19
$ node dist/apps/cli/main.js info
INFO
=========
Yarn: 1.22.19
Node: v18.9.0
Dash: 4.5.2

Cwd: /app
Hash: afb66c4801e68076ad4562ba67636f05120f9e9a
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.39s.
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Where is your instance running?

Other (Please specify below)

### Additional context

Proxmox running an Debian 11 LXC Container with Docker installed. Tried two different Physical Systems.

**Comment by MauriceNino** [comment]
Hello there, thanks for creating the issue. The storage split view only works on systems with 2 or more drives installed. Can you send me the part of the log where it gathers the static info, especially the storage info?

**Comment by MauriceNino** [comment]
Closed due to inactivity
