### ISSUE TITLE
[Feature] add SpeedTest history and ping graph.

### ISSUE THREAD

**Issue by hillaliy** [MauriceNino/dashdot#415]
### Description of the feature

Hi it will be nice if you will add graph for internet speedtest (download / upload) and Ping by hours.
<img width="958" alt="speedtest" src="https://user-images.githubusercontent.com/950010/197410454-b5edf955-e993-4c63-83d8-d319510e2ee5.png">

**Comment by MauriceNino** [comment]
Hey there, thanks for the issue. Unfortunately, I feel like this is out of the scope of the project and I don't see a good way where this fits. In case someone else wants to implement this, please have a talk with me, but I personally don't think this will be a good addition.
