### ISSUE TITLE
[Feature] GPU Monitoring

### ISSUE THREAD

**Issue by jeryd** [MauriceNino/dashdot#43]
Feature request: GPU Monitoring

Let me know how hard my GPU is working.

**Comment by MauriceNino** [comment]
Thank you for this feature request! I have already started testing features around this, but had troubles with reading GPU stats through WSL2. I will try again using my Laptop running Ubuntu.

But on a second note, this will be an optional feature, as this repository is meant to be used primarily for servers, where GPUs are mostly irrelevant.

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 3.6.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/CHANGELOG.md) for more details.

**Comment by MauriceNino** [comment]
FYI: It's really hard to get GPUs running in a docker container, so you are probably best off to install dashdot from source.
