### ISSUE TITLE
[Feature] Performance improvements for mobile

### ISSUE THREAD

**Issue by myNicole98** [MauriceNino/dashdot#549]
Dash. has poor performance according to pagespeed. Some optimization would be appreciated, especially if it is being used as an integration for other services (e.g. Homarr)

![immagine](https://user-images.githubusercontent.com/74139268/214857966-b9993fa4-7ce7-4302-8b47-bcd9731f1088.png)
![immagine](https://user-images.githubusercontent.com/74139268/214858010-9eef4971-01aa-4746-a21d-528d3270787f.png)

**Comment by MauriceNino** [comment]
I managed to get about half the loading time. I think a modern smartphone will now work very well with dashdot.

On mobile:

![image](https://user-images.githubusercontent.com/18658092/215143881-e2d54475-3bc1-4ff6-8ac1-bf3d022f66a9.png)

On desktop:

![image](https://user-images.githubusercontent.com/18658092/215144179-76d8b8f8-21b0-4520-b0bc-14aca3ff7588.png)

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 4.7.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/.github/CHANGELOG.md) for more details.
