### ISSUE TITLE
[Feature] Allow external SpeedTest data

### ISSUE THREAD

**Issue by micalm** [MauriceNino/dashdot#558]
### Description of the feature

Some people (like me) are already running external speedtests for stuff like Prometheus. Would it be possible to use something like `DASHDOT_SPEED_FILE=/path/to/file.json` to read these results instead of running a separate binary and test, wasting network resources?

It would also solve the issue for people who don't want to run speed tests at all while providing a scale for the network graph (#288). The file would be static then.

Obviously the JSON is only a suggestion, could very well be csv/tsv or anything else - up to external scripts to provide the data in dashdot-readable format.

**Comment by MauriceNino** [comment]
That's a great idea, thanks for that! Did I understand that correctly - the file can be generated in any format, so it's up to me to provide a good format? Or is there a universal format already given?

**Comment by micalm** [comment]
I don't think there is a standard (not 100% sure), so it's up to you to specify it. IMO basing it on Ooklas json would be fine.

**Comment by MauriceNino** [comment]
I just implemented this, and it will go live in ~2h. You can check out the docs [here](https://getdashdot.com/docs/config/featuresdashdot_speed_test_from_path), once it's released. Hope this fits your needs!

**Comment by MauriceNino** [comment]
:tada: This issue has been resolved in version 4.8.0

Please check the [changelog](https://github.com/MauriceNino/dashdot/blob/main/.github/CHANGELOG.md) for more details.
