### ISSUE TITLE
[Feature] FR - IP address 

### ISSUE THREAD

**Issue by jeryd** [MauriceNino/dashdot#57]
### Description of the feature

If possible, could dash. show the IP of the device (WAN and or LAN) under the new NETWORKING section?

**Comment by MauriceNino** [comment]
It would definitely be possible, but why would you want this?

**Comment by jeryd** [comment]
because I don't know what ip my servers are using and it would be nice to quickly check. I normally access them through a vpn (tailscale).

**Comment by MauriceNino** [comment]
I am not sure, if that is something that fits in this project. I think I will make all the labels more configurable, then I can add it as an optional label.
