### ISSUE TITLE
[Bug] df does not return all drives inside the container

### ISSUE THREAD

**Issue by MauriceNino** [MauriceNino/dashdot#59]
### Description of the bug

Drive information is gathered using `df`, which returns only the root drive `/` inside the docker container, while it returns all drives on the host.

This should not be the case, because with `--privileged`, all devices should be available inside the container.

BUT - the device is actually mounted, which can be seen when using `ls -la /dev`

### How to reproduce

Connect to the docker container and run `df`:

```
docker container exec -it CONTAINER_NAME /bin/sh -c "df"
```

And check that it is mounted with:

```
docker container exec -it CONTAINER_NAME /bin/sh -c "ls -la /dev/DRIVE_NAME"
```

### Additional Context

I have opened a StackOverflow question with a bounty: https://stackoverflow.com/q/72517164/9150652

**Comment by MauriceNino** [comment]
If the SO question results in no answers, I will create a temporary solution where users have to mount `-v /dev/:/mnt/host/` until this really gets resolved.

**Comment by CyberiumShadow** [comment]
On Raspberry Pi 4, it also doesn't correctly show storage either.

**Comment by MauriceNino** [comment]
Temporarily fixed with volume mounts. If there is a better solution, I will create a new issue for it.
