### ISSUE TITLE
[Bug] White screen when first time loading.

### ISSUE THREAD

**Issue by LarveyOfficial** [MauriceNino/dashdot#689]
### Description of the bug

I do not know if this is something I did, but I have dashdot running in a docker container and behind NGINX Proxy Manager.

When loading the page for the first time, it is just a white screen.

### How to reproduce

When I load my site in incognito
![image](https://user-images.githubusercontent.com/39219859/233123150-18636416-a1da-44d6-9b53-6fcefdee014d.png)

When I do Ctrl + R, it loads, but if I do a simple refresh it does not load.

### Relevant log output

I get the following in every Browser's console:
```
blicPath:14 Uncaught Error: Automatic publicPath is not supported in this browser
    at publicPath:14:23
    at runtime.fcde5ccb6403af5a.esm.js:1:2716
    at runtime.fcde5ccb6403af5a.esm.js:1:3509
```

### Info output of dashdot cli

```shell
INFO
=========
Yarn: 1.22.19
Node: v18.15.0
Dash: 5.1.3

Cwd: /app
Hash: 386191c474baca48d35d655bf77a8b4953e8645b
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.67s.
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Where is your instance running?

Linux Server

### Additional context

I have it also behind a Cloudflare proxy

**Comment by MauriceNino** [comment]
Thanks for reporting this. Is it also happening on the [public demo](https://dash.mauz.dev/) for you, or only your local instance?

**Comment by LarveyOfficial** [comment]
Although when going to the demo it does have a white screen, but only for a second, then it seems to update itself and load correctly with no errors.

**Comment by LarveyOfficial** [comment]
I have done some testing, and have come to the conclusion that for some reason cloudflare seems to be part of the issue. I will keep investigating further.

**Comment by LarveyOfficial** [comment]
Ok, I don't know if this can be considered an issue here. Although I only have ever had this issue with dashdot.
But Cloudflare's Bot Fight Mode seems to cause the error stated earlier.
Disabling it seems to solve the issue, but I am hoping something can be done so that enabling it isn't a problem.
https://developers.cloudflare.com/bots/reference/javascript-detections

**Comment by LarveyOfficial** [comment]
Ok, I don't know if this can be considered an issue here. Although I only have ever had this issue with dashdot.
But Cloudflare's Bot Fight Mode seems to cause the error stated earlier.
Disabling it seems to solve the issue, but I am hoping something can be done so that enabling it isn't a problem.
https://developers.cloudflare.com/bots/reference/javascript-detections

**Comment by MauriceNino** [comment]
Thanks for looking into this some more! Can you maybe investigate where in my code the error is thrown?
It looks like you don't have source maps (which is strange), so maybe clicking on `runtime.fcde5ccb6403af5a.esm.js:1:2716` and making a screenshot could help.

It could also be, that `runtime.fcde5ccb6403af5a.esm.js:1:2716` is part of the JS that Cloudflare injects - in that case I think we would need to file an issue with them.

**Comment by LarveyOfficial** [comment]
It seems you use @nrwl/react/plugins/webpack for your webpack config, some people where having a similar issue, and have solved it by creating a custom webpack config file
https://github.com/nrwl/nx/issues/10163

**Comment by MauriceNino** [comment]
Yea I already found that solution as well, but I am hesitant to add that, because I don't know what it might break for someone else and also I would like to avoid creating a custom webpack config.

I would really like to know what part is failing exactly and why, so maybe I could find another fix that is not as intrusive.

**Comment by MauriceNino** [comment]
@LarveyOfficial Can you please click on the files that are shown in the error and post a screenshot of what code you see there?

```
blicPath:14 Uncaught Error: Automatic publicPath is not supported in this browser
    at publicPath:14:23 // <-- here
    at runtime.fcde5ccb6403af5a.esm.js:1:2716 // <-- & here
    at runtime.fcde5ccb6403af5a.esm.js:1:3509 // <-- & here
```

**Comment by LarveyOfficial** [comment]
**publicPath**
`var scriptUrl;
if (__webpack_require__.g.importScripts) scriptUrl = __webpack_require__.g.location + "";
var document = __webpack_require__.g.document;
if (!scriptUrl && document) {
	if (document.currentScript)
		scriptUrl = document.currentScript.src
	if (!scriptUrl) {
		var scripts = document.getElementsByTagName("script");
		if(scripts.length) scriptUrl = scripts[scripts.length - 1].src
	}
}
// When supporting browsers where an automatic publicPath is not supported you must specify an output.publicPath manually via configuration
// or pass an empty string ("") and set the __webpack_public_path__ variable from your code to use your own logic.
if (!scriptUrl) throw new Error("Automatic publicPath is not supported in this browser");
scriptUrl = scriptUrl.replace(/#.*$/, "").replace(/\?.*$/, "").replace(/\/[^\/]+$/, "/");
__webpack_require__.p = scriptUrl;`

** runtime.fcde5ccb6403af5a.esm.js**
`(() => {
    "use strict";
    var e, r, t, o, n = {},
        i = {};

    function a(e) {
        var r = i[e];
        if (void 0 !== r) return r.exports;
        var t = i[e] = {
            id: e,
            loaded: !1,
            exports: {}
        };
        return n[e].call(t.exports, t, t.exports, a), t.loaded = !0, t.exports
    }
    a.m = n, e = [], a.O = (r, t, o, n) => {
        if (!t) {
            var i = 1 / 0;
            for (s = 0; s < e.length; s++) {
                for (var [t, o, n] = e[s], l = !0, u = 0; u < t.length; u++)(!1 & n || i >= n) && Object.keys(a.O).every((e => a.O[e](t[u]))) ? t.splice(u--, 1) : (l = !1, n < i && (i = n));
                if (l) {
                    e.splice(s--, 1);
                    var c = o();
                    void 0 !== c && (r = c)
                }
            }
            return r
        }
        n = n || 0;
        for (var s = e.length; s > 0 && e[s - 1][2] > n; s--) e[s] = e[s - 1];
        e[s] = [t, o, n]
    }, a.n = e => {
        var r = e && e.__esModule ? () => e.default : () => e;
        return a.d(r, {
            a: r
        }), r
    }, t = Object.getPrototypeOf ? e => Object.getPrototypeOf(e) : e => e.__proto__, a.t = function(e, o) {
        if (1 & o && (e = this(e)), 8 & o) return e;
        if ("object" == typeof e && e) {
            if (4 & o && e.__esModule) return e;
            if (16 & o && "function" == typeof e.then) return e
        }
        var n = Object.create(null);
        a.r(n);
        var i = {};
        r = r || [null, t({}), t([]), t(t)];
        for (var l = 2 & o && e;
            "object" == typeof l && !~r.indexOf(l); l = t(l)) Object.getOwnPropertyNames(l).forEach((r => i[r] = () => e[r]));
        return i.default = () => e, a.d(n, i), n
    }, a.d = (e, r) => {
        for (var t in r) a.o(r, t) && !a.o(e, t) && Object.defineProperty(e, t, {
            enumerable: !0,
            get: r[t]
        })
    }, a.f = {}, a.e = e => Promise.all(Object.keys(a.f).reduce(((r, t) => (a.f[t](e, r), r)), [])), a.u = e => e + ".920310a31bf3f30a.esm.js", a.miniCssF = e => {}, a.g = function() {
        if ("object" == typeof globalThis) return globalThis;
        try {
            return this || new Function("return this")()
        } catch (e) {
            if ("object" == typeof window) return window
        }
    }(), a.o = (e, r) => Object.prototype.hasOwnProperty.call(e, r), o = {}, a.l = (e, r, t, n) => {
        if (o[e]) o[e].push(r);
        else {
            var i, l;
            if (void 0 !== t)
                for (var u = document.getElementsByTagName("script"), c = 0; c < u.length; c++) {
                    var s = u[c];
                    if (s.getAttribute("src") == e) {
                        i = s;
                        break
                    }
                }
            i || (l = !0, (i = document.createElement("script")).charset = "utf-8", i.timeout = 120, a.nc && i.setAttribute("nonce", a.nc), i.src = e), o[e] = [r];
            var f = (r, t) => {
                    i.onerror = i.onload = null, clearTimeout(d);
                    var n = o[e];
                    if (delete o[e], i.parentNode && i.parentNode.removeChild(i), n && n.forEach((e => e(t))), r) return r(t)
                },
                d = setTimeout(f.bind(null, void 0, {
                    type: "timeout",
                    target: i
                }), 12e4);
            i.onerror = f.bind(null, i.onerror), i.onload = f.bind(null, i.onload), l && document.head.appendChild(i)
        }
    }, a.r = e => {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }), Object.defineProperty(e, "__esModule", {
            value: !0
        })
    }, a.nmd = e => (e.paths = [], e.children || (e.children = []), e), (() => {
        var e;
        a.g.importScripts && (e = a.g.location + "");
        var r = a.g.document;
        if (!e && r && (r.currentScript && (e = r.currentScript.src), !e)) {
            var t = r.getElementsByTagName("script");
            t.length && (e = t[t.length - 1].src)
        }
        if (!e) throw new Error("Automatic publicPath is not supported in this browser");
        e = e.replace(/#.*$/, "").replace(/\?.*$/, "").replace(/\/[^\/]+$/, "/"), a.p = e
    })(), (() => {
        var e = {
            666: 0
        };
        a.f.j = (r, t) => {
            var o = a.o(e, r) ? e[r] : void 0;
            if (0 !== o)
                if (o) t.push(o[2]);
                else if (666 != r) {
                var n = new Promise(((t, n) => o = e[r] = [t, n]));
                t.push(o[2] = n);
                var i = a.p + a.u(r),
                    l = new Error;
                a.l(i, (t => {
                    if (a.o(e, r) && (0 !== (o = e[r]) && (e[r] = void 0), o)) {
                        var n = t && ("load" === t.type ? "missing" : t.type),
                            i = t && t.target && t.target.src;
                        l.message = "Loading chunk " + r + " failed.\n(" + n + ": " + i + ")", l.name = "ChunkLoadError", l.type = n, l.request = i, o[1](l)
                    }
                }), "chunk-" + r, r)
            } else e[r] = 0
        }, a.O.j = r => 0 === e[r];
        var r = (r, t) => {
                var o, n, [i, l, u] = t,
                    c = 0;
                if (i.some((r => 0 !== e[r]))) {
                    for (o in l) a.o(l, o) && (a.m[o] = l[o]);
                    if (u) var s = u(a)
                }
                for (r && r(t); c < i.length; c++) n = i[c], a.o(e, n) && e[n] && e[n][0](), e[n] = 0;
                return a.O(s)
            },
            t = self.webpackChunk = self.webpackChunk || [];
        t.forEach(r.bind(null, 0)), t.push = r.bind(null, t.push.bind(t))
    })(), a.nc = void 0
})();
//# sourceMappingURL=runtime.fcde5ccb6403af5a.esm.js.map`

**Comment by MauriceNino** [comment]
I just enabled Cloudflare bot protection for the public demo, but still can't reproduce this issue in Chrome.

But also there are some recent updates, so can you please try the following two things:

1. Open <https://dash.mauz.dev/> and see if the issue exists for your
2. Pull the latest dev image (`mauricenino/dashdot:dev`) and try if that works with your bot protection

**Comment by MauriceNino** [comment]
Ok, I just enabled Cloudflare for the public demo and can now reproduce this issue (after some waiting time). It seems to be resolved through the latest switch from CRA to Vite. Can you confirm that this behavior is true for you as well?

1. <https://dash.mauz.dev>: fails on first load
2. <https://dash-dev.mauz.dev>: works on first load

**Comment by MauriceNino** [comment]
Okay, Cloudflare is messing with some other services of mine, so I had to shut it down. Please pull the latest dev image (`mauricenino/dashdot:dev`) and try it yourself.

**Comment by MauriceNino** [comment]
@LarveyOfficial are you still available for a short test?

**Comment by SpaceNerden** [comment]
@MauriceNino Not Larvey but I can confirm the dev image works with the cloudflare proxy [here](https://dash.spacenerden.dev/)

Thanks for the fix!

**Comment by MauriceNino** [comment]
@SpaceNerden Thank you for testing - do you also have `Bot Fight Mode` enabled on your instance?

**Comment by SpaceNerden** [comment]
> @SpaceNerden Thank you for testing - do you also have `Bot Fight Mode` enabled on your instance?

I turned it on to "I am under attack!" mode, and it still works.

**Comment by LarveyOfficial** [comment]
"I am under attack!" and "Bot Fight Mode" are different, while "I am under attack!" also does Bot fighting mode, it has a delay/longer loading time. So to actually test you have to specifically use "Bot Fight Mode" not "I am under attack!"

**Comment by LarveyOfficial** [comment]
I've been on vacation for a bit so I am not able to test right now. I also think I am just on the main image.
Once I am back home I can do some testing.

**Comment by MauriceNino** [comment]
I will close that issue for now, as it seems to be fixed already. If anything is still not working, LMK and I will reopen it.
