### ISSUE TITLE
[Bug] Public IP exposed even when overwritten.

### ISSUE THREAD

**Issue by LarveyOfficial** [MauriceNino/dashdot#690]
### Description of the bug

Even when you overwrite the public IP as an environment variable in the config, when going to /info, the public IP is still exposed.

### How to reproduce

Simply go to /info in the docker container and it will expose your public IP, only way to prevent this is to feed it a custom speedtest json with a fake public IP.

### Info output of dashdot cli

```shell
INFO
=========
Yarn: 1.22.19
Node: v18.15.0
Dash: 5.1.3

Cwd: /app
Hash: 386191c474baca48d35d655bf77a8b4953e8645b
In Docker: true
In Podman: false
In Docker (env): true
Done in 0.67s.
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Where is your instance running?

Linux Server

**Comment by LarveyOfficial** [comment]
I personally use Cloudflare proxy to hide my public IP, which means anyone can technically go to /info and see my public IP, even when I try to have it hidden.

**Comment by MauriceNino** [comment]
Oh okay that makes total sense. I will look into this.
