### ISSUE TITLE
[Bug] Error: Command failed: cat /sys/class/net/ppp0/speed

### ISSUE THREAD

**Issue by easonyen16** [MauriceNino/dashdot#715]
### Description of the bug

I am running dashdot from source.
After installing, I type in sudo -E yarn start to start it, it show the error

### How to reproduce

`sudo -E yarn start`

### Relevant log output

```shell
Version file not found. This is normal on from-source builds.
listening on *:3001
Multiple default network interfaces found [ppp0, eth0], using "ppp0"
Using default network interface "ppp0"
Using host os version from "/etc/os-release"
(node:1114655) UnhandledPromiseRejectionWarning: Error: Command failed: cat /sys/class/net/ppp0/speed
cat: /sys/class/net/ppp0/speed: Invalid argument
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12)
(node:1114655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1114655) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.
```

### Info output of dashdot cli

```shell
INFO
=========
Yarn: 3.5.0
Node: v18.15.0
Dash: unknown
Cwd: /home/yanyixuan/dashdot
Hash: c6cb25447599a94fc7955b5ccb680a61d0c97d5e
In Docker: false
In Podman: false
In Docker (env):
```

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Raspberry Pi

### Additional context

In my browsers it shows
![Screenshot_20230428_020437_Chrome](https://user-images.githubusercontent.com/57711962/234953193-c7dc1822-c788-4d13-8076-a30bafbb95b9.jpg)

**Comment by MauriceNino** [comment]
Hi there, can you by any chance post the output of this command:
```
route | grep '^default' | grep -o '[^ ]*$'
```
or
```
ip route get 8.8.8.8 | sed -n 's/.*dev \([^\ ]*\).*/\1/p'
```
---

If that doesn't work, please have a look at [this StackExchange post](https://unix.stackexchange.com/questions/14961/how-to-find-out-which-interface-am-i-using-for-connecting-to-the-internet) for another method of finding out your main network interface.

What I suspect is that `ppp0` is not your actual network interface and there is some weirdness happening.

**Comment by easonyen16** [comment]
```
yanyixuan@raspberrypi:~ $ route | grep '^default' | grep -o '[^ ]*$'
ppp0
eth0
yanyixuan@raspberrypi:~ $ ip route get 8.8.8.8 | sed -n 's/.*dev \([^\ ]*\).*/\1/p'
ppp0
```

**Comment by MauriceNino** [comment]
So I just pushed a new version on the dev branch, could you please try that out?

```
docker image pull mauricenino/dashdot:dev
docker container run -it --rm --privileged -v /:/mnt/host:ro -p 3002:3001 mauricenino/dashdot:dev
```

**Comment by MauriceNino** [comment]
@SuimgPhilip You are having similar issues, so could you please also try out that solution?

**Comment by easonyen16** [comment]
Thank you!
It can run now.
<img width="1552" alt="截圖 2023-04-29 下午9 25 12" src="https://user-images.githubusercontent.com/57711962/235305219-b4d00c5e-085e-47d4-a984-1ba197584896.png">

**Comment by SuimgPhilip** [comment]
> @SuimgPhilip You are having similar issues, so could you please also try out that solution?

The problem is solved
