### ISSUE TITLE
[Bug] Cant get speedtest to work on windows

### ISSUE THREAD

**Issue by vishal272** [MauriceNino/dashdot#729]
### Description of the bug

I have installed speedtest CLI as well as added the path entry for it. I can run speedtest.exe from the dashdot directory but when running yarn start i keep getting the prompt

Error: There is no speedtest module installed - please use one of the following:
- speedtest: https://www.speedtest.net/apps/cli
- speedtest-cli: https://github.com/sivel/speedtest-cli

Im not sure if i have missed something but i cant seem to get this to work

**Comment by MauriceNino** [comment]
Hi, thanks for creating an issue. I have released a test build that might fix your problem. Can you please try checking out the branch `feature/windows-speedtest-fix` and rebuild from there?

**Comment by vishal272** [comment]
Thanks for that this seems to have solved it.

**Comment by MauriceNino** [comment]
Perfect - this will be released shortly in the next main release!
