### ISSUE TITLE
[Feature] Support Compose Labels for an instant configuratiom

### ISSUE THREAD

**Issue by zilexa** [MauriceNino/dashdot#770]
### Description of the feature

Please consider supporting Docker Compose Labels. That way, the dashboard is automatically populated and additional configuration becomes optional. 

For an example, see Plugsy:
https://github.com/plugsy/core

It's extremely simple to have an instant dashboard this way. With categories and parents etc.

**Comment by MauriceNino** [comment]
Sorry, but I don't think this fits the project? Configuration is done via environment variables (and will be switched to yaml files in the near future). Unset variables fall back to a default value, so additional configuration is already optional.

It seems like you mistake Dashdot for a personal dashboard, where you display running services (like Homarr, Flame, ...) - this project does not offer such features.

**Comment by zilexa** [comment]
I re-read the documentation, very sorry, my mistake!
