### ISSUE TITLE
[Bug] Dashdot fails to find speedtest on Windows

### ISSUE THREAD

**Issue by caesay** [MauriceNino/dashdot#884]
### Description of the bug

When building from source on Windows, dashdot fails to find the speedtest executable because the line of code which checks for the speedtest utility uses the `which` command. This command does not exist on windows, instead you must use the `where` command. 

The code requiring the patch is here: https://github.com/MauriceNino/dashdot/blob/ce89dff8fccd702bac9a4bd9038904ecdc012555/apps/api/src/data/network.ts#L13

### How to reproduce

1. Download the `speedtest.exe` utility and place it on the path
2. Follow the "building from source" instructions
3. Run dashdot and receive the error: There is no speedtest module installed

**Comment by MauriceNino** [comment]
Ehh right, that is already fixed, just not released. Will do so right now. Thanks for reporting it though.

**Comment by MauriceNino** [comment]
Unfortunately, I can't release the docker version right now (#885), but as you are using git, you can just pull the latest changes and run them anyway.
