### ISSUE TITLE
[Feature] Server Power control

### ISSUE THREAD

**Issue by ThaDaVos** [MauriceNino/dashdot#887]
### Description of the feature

The panel already looks amazing! The one thing I think is missing is control of the machine itself, like rebooting/power off etc

**Comment by MauriceNino** [comment]
Hello there, thanks for creating this feature request, but unfortunately, I don't see this making its way into the project. Dashdot was never meant to have any administrative control over a machine - it should be strictly reading data. For what you are trying to do, I would recommend other services (maybe a personal dashboard like Homarr can do the job?)
