### ISSUE TITLE
[Feature] How to monitor host traffic

### ISSUE THREAD

**Issue by starmisszhang** [MauriceNino/dashdot#912]
### Description of the feature

Only Docker traffic can be displayed，“DASHDOT_USE_NETWORK_INTERFACE ” How should I fill it out "/proc/1/ns/net:/mnt/host/proc/1/ns/net"  This doesn't work either

**Comment by MauriceNino** [comment]
Docker should be able to mount the host network, by using the volume mount `-v /:/mnt/host:ro`. If that doesn't work, please create a bug ticket for this and provide the necessary information (like logs).

A workaround would be to enable host networking on your docker container.
