### ISSUE TITLE
[Feature] Timestamp for speedtest data.

### ISSUE THREAD

**Issue by dng-nguyn** [MauriceNino/dashdot#915]
### Description of the feature

Hello! I've been using dash. for a while now and I found the speedtest do not have timestamps/last time since the speedtest ran. It would be awesome to have a configurable option to show the last time the speedtest was done, so I know whether it was during peak or off hours and diagnose my internet if necessary.

**Comment by MauriceNino** [comment]
Hi there, sorry for the late reply. Yes, that makes sense and should be pretty easy to add. I will add it when I get some time.
