### ISSUE TITLE
[Feature]  Will there be the ability to add more hosts for one webinterface

### ISSUE THREAD

**Issue by scharez** [MauriceNino/dashdot#919]
### Description of the feature

Will there be the ability to add more hosts to one webinterface in the feature?

**Comment by MauriceNino** [comment]
Hello, unfortunately no as this would require a complete rebuild and was never the goal of the project.

What I can recommend you, is that you host one instance per host and then accumulate them on some kind of dashboard via the [Widgets](https://getdashdot.com/docs/integration/widgets).

If you want, you can use an existing solution like [Homarr](https://homarr.dev/), which integrates with Dash. perfectly [see here](https://homarr.dev/docs/widgets/dashdot-widget).

**Comment by scharez** [comment]
Hi, thank you for your quick reply.

I haven't thought of the widgets. However, do you know how can i like password protect the webinterface? I mean i can use basic auth in the reverse proxy. But what if i want to display the widget in my self written admin dashboard?

Do you have any idea?
