### ISSUE TITLE
[Feature] Drives show up instead of partitions

### ISSUE THREAD

**Issue by Ahwxx** [MauriceNino/dashdot#92]
Dashdot shows my drives instead of partitions.

Example: [stats.jaapvd.nl](https://stats.jaapvd.nl)

**Comment by MauriceNino** [comment]
Well dash. is more of a hardware viewer, than a configuration viewer, so I think this is nothing that I personally will implement. 

I will leave it open as a feature request, in case someone wants to implement this as an optional feature.
