### ISSUE TITLE
[Feature] Make a cool sidebar.

### ISSUE THREAD

**Issue by steveiliop56** [MauriceNino/dashdot#922]
### Description of the feature

Dashdot has an extremely cool ui but has something that I don't like... In small screens the default chrome sidebar appears and destroys the cool built ui. So a good solution would be to add custom one like uptime-kuma here: 
<img  alt="image" src="https://github.com/MauriceNino/dashdot/assets/106091011/0f42f69a-59c8-4be1-8052-4afd1de47b8b">

**Comment by MauriceNino** [comment]
Hi there. Yes, that would look really nice I think! Thanks for the input!

**Comment by steveiliop56** [comment]
Hello @MauriceNino! When do you think this will be ready?

**Comment by MauriceNino** [comment]
Probably not a priority right now, as there are a lot of important issues to be fixed frist, and I am low on time already. But feel free to create a PR and if it works nicely, we can go from there.
