### ISSUE TITLE
[Bug] Sometimes speed test stops working and reports 0000000 

### ISSUE THREAD

**Issue by dopeytree** [MauriceNino/dashdot#928]
### Description of the bug

[Bug] Sometimes speed test stops working and reports 0000000 

### How to reproduce

unknown 

### Relevant log output

```shell
Running speed-test (this may take a few minutes)...
First measurement [Network]: { up: null, down: null }
First measurement [Storage]: [
  25576513536, 0, 0,
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
            0
]
```

### What browsers are you seeing the problem on?

Safari

### Where is your instance running?

Other (Please specify below)

### Additional context

Unraid (linux: docker)

**Comment by dopeytree** [comment]
Is fixed by re-starting container

**Comment by MauriceNino** [comment]
As there is no update on this issue and there seems to be no one else reporting this problem, I will close this for now. Please comment if you encounter this issue, so I can reopen it.
