### ISSUE TITLE
[Bug]  UI not alligned correctly

### ISSUE THREAD

**Issue by jeryd** [MauriceNino/dashdot#93]
### Description of the bug

Something fishy is happening with the UI.
![Screenshot 2022-06-02 201052](https://user-images.githubusercontent.com/4661200/171779097-96396aa3-8ac1-4ab2-9a5b-745d295b7526.png)

The button/switch to show all cores and the button/switch for dark mode is overlapping and not in the correct spot.

### What browsers are you seeing the problem on?

Firefox

### Where is your instance running?

Other (Please specify below)

### Additional context

UnRaid Sever

**Comment by MauriceNino** [comment]
Can you share your configuration and browser console output? Also, what version are you running?

**Comment by jeryd** [comment]
Firefox / 101.0.
Double checked - Dash. works as expected in edge. (running latest Dash. version)
Dash. works as expected on a different server (which is running [v2.2.1]) in Firefox

**Comment by MauriceNino** [comment]
So the issue only appears on latest (2.3.0) in Firefox, did I get that right?

**Comment by MauriceNino** [comment]
The issue should be fixed in the next version (released in a few days, because I want to put in some more features, as it will be a major release)

**Comment by MrAlucardDante** [comment]
I would like to reopen this issue, as it is still there on both Chrome and Firefox

**Comment by MauriceNino** [comment]
Are you sure you did update? Can you please open <https://dash.mauz.io/>, which is running the latest release and check if the error appears there as well?

If not, you should probably need to run `docker pull mauricenino/dashdot:latest` and then restart your deployment.
@MrAlucardDante

**Comment by MrAlucardDante** [comment]
I am running 3.0.0 (which is equal to latest). Same issue on both firefox and chrome, even on dash.mauz.io. i disabled my adblocker too
![image](https://user-images.githubusercontent.com/20476382/172340362-5ef6c824-37cb-455b-ac5d-cf31d68c7653.png)

**Comment by MauriceNino** [comment]
The buttons seem to be at the correct spot, though?
The issues with the color must be because of some configuration on your side, but I honestly don't know what it could be. 
Have you looked into the log?

If you are absolutely certain, that this is not a configuration on your side, please open another issue, as this looks like something completely different than #93.

**Comment by MrAlucardDante** [comment]
My bad, I glanced over the issue description and I thought the OP meant that the graphs and icon were overflowing the boxes behind it. The buttons are OK. Sorry for wasting your time

**Comment by MauriceNino** [comment]
Ahh, okay - got it, no worries!
The overflowing boxes and icons are per design - they should give the widgets more depth :)

Would you like an option to disable this behavior?

Also, the color on your widget really are off a little - is this a configuration on your client, or should I look into this?

**Comment by MrAlucardDante** [comment]
I am ok with the boxes overflowing, I thought it was a bug. The colors being off is normal, I am using the Dark Reader extensions ;)
