### ISSUE TITLE
[Feature] Allow users to change the unit of Internet speed from Mb/s to MB/s

### ISSUE THREAD

**Issue by kerryfangda89** [MauriceNino/dashdot#930]
### Description of the feature

Out of different habits, I feel more comfortable displaying it as MB/s. Mind if adding it as a new environment variable? Thank you!

**Comment by flashorsink** [comment]
Agree, need MB/s!

**Comment by zfxkj** [comment]
I also agree to convert Mb/s to MB/s.

**Comment by SandroBarillaPXL** [comment]
Would be nice, yesi

**Comment by MauriceNino** [comment]
You can now switch to MB/s by passing [`DASHDOT_NETWORK_SPEED_AS_BYTES="true"`](https://getdashdot.com/docs/config/ui-features#dashdot_network_speed_as_bytes) to your dashdot instance.
