### ISSUE TITLE
[Bug] CPU temp doesn't show the max temp

### ISSUE THREAD

**Issue by tuxrinku** [MauriceNino/dashdot#932]
### Description of the bug

I have an i5 13600K and dashdot doesn't show the current max temp on the cpu. From what it looks like, I'd say it takes temp of e-cores instead of p-cores. The `sensors` command shows appropriate temps for each core.

### Where is your instance running?

Home desktop computer, running Ubuntu 23.04

**Comment by quadcom** [comment]
I think this is because the temps are not taken from the package temperature. In my case I see the reported temps at 77deg when the package temps are 82deg. 

It would be great if we could define the temp source for the CPU reporting.

![image](https://github.com/MauriceNino/dashdot/assets/7085931/c41247a3-af80-4924-860f-ea2f809cc9f7)

**Comment by MauriceNino** [comment]
The CPU temperature is gathered per-core and then averaged out in the UI. In case per-core temperature data is not available, the "main" temperature is taken (the average of all cores) and applied to each core. The result should technically be the same.

The question is, what temperature is more interesting to you, and why?

Will also change the issue type to `feature`, as this currently seems to be working as intended.

**Comment by tuxrinku** [comment]
Thank you for looking into it. The max temperature is the most interesting for me, because it allows to keep an eye on the CPU package and see if you get close to the throttling threshold or not.

**Comment by MauriceNino** [comment]
Ah okay, got it. I suspect that the temperature you are looking for is either the `socket` or the `chipset` one? Not too much into hardware, so I don't really know the difference.

Can you maybe try checking the following command?

```
docker exec CONTAINER yarn cli raw-data --cpu
```

The output should contain an object named `cpuTemp`. Can you run this a few times and research which property matches the desired temperature reading you would like?

**Comment by tuxrinku** [comment]
Here's the output :
`const cpuTemp =  {
  main: 43,
  cores: [ 43, 43, 44, 43 ],
  max: 44,
  socket: [ 27.8 ],
  chipset: null
}`

So I'd need the max property of this object

**Comment by MauriceNino** [comment]
Ah, okay, got it! I will add a config flag like `DASHDOT_CPU_TEMPERATURE_MODE` with the options `max` and `average`, where `average` is the default value.

**Comment by tuxrinku** [comment]
Perfect ! Thank you.

**Comment by MauriceNino** [comment]
The config variable is called `DASHDOT_CPU_TEMPS_MODE` and has the options `max` and `avg`. After the new version is deployed, you can pull the image and use it.

**Comment by tuxrinku** [comment]
For some reason it still doesn't show the max temp, even tho I have `cpu_temps_mode: 'max'` enabled. I'm using it directly from sources if that matters

**Comment by MauriceNino** [comment]
Thanks for letting me know, I will look into those issues, once I have more time to investigate.

**Comment by MauriceNino** [comment]
@tuxrinku I have just tested it locally and both those options seem to work for me. Are you sure that you correctly updated to the latest version?

For local installs, this should be done using `git fetch && git pull`.

**Comment by tuxrinku** [comment]
Yes, thank you now it's working perfectly. I guess I pulled it too soon
