### ISSUE TITLE
[Feature]  clickable graphs / allow other services to provide the indepth details

### ISSUE THREAD

**Issue by lazee486** [MauriceNino/dashdot#933]
### Description of the feature

I'd like to for example, click the disks and open scrutiny or doku, for the cpu -> glances, etc (still looking for a nework one that looks like glasswire lol) , making customizable links would let me use this as my server landing page and any indepth stuff with other projects without having to do much here.
my vision is this page being my homelab/vps landing, beautiful and informative and using other specialized tools for details, without having to see the disk usage is high here, then go to a dashboard, then to scrutiny...so looks and convenience :) 

Ive noticed i can display multiple dash. servers in Homarr - so going there next to see if can make those clickable too...
keep up the amazing work :)

**Comment by MauriceNino** [comment]
Hi there, thanks for the input!

Unfortunately, I am not sure that I want to go into that direction, as I don't really feel like it fits the project. The preferred solution would be to use Homarr and implement dashdot as a widget there, Or create your own landing page with the customizable widgets using the [Widget Creator](https://getdashdot.com/docs/integration/widgets#widget-creator).

I hope that fits your needs!
