### ISSUE TITLE
[Feature] Request - Custom labels for storage

### ISSUE THREAD

**Issue by ServerGeek82** [MauriceNino/dashdot#937]
### Description of the feature

To do custom labels for the drives  or mounts on the host in the dashboard. Love the layout, the simplicity, and ease. Absolutely amazing work on this project.

Before: 
Drive	HP HD
=> 558.9 GiB
Drive	HP HD
=> 10.9 TiB

After:
Drive	OS Drive
=> 558.9 GiB
Drive	Plex1
=> 10.9 TiB

**Comment by SpeakingOfBrad** [comment]
You can already do that with `DASHDOT_OVERRIDE_STORAGE_BRANDS`.
For example:
```
  --env DASHDOT_OVERRIDE_STORAGE_BRANDS="sda=OS Drive,sdb=Media Server,sdc=File Server" \
```

**Comment by ServerGeek82** [comment]
Will try this out in a few days. Thanks a bunch. Now just to be able to show all my drives.

**Comment by MauriceNino** [comment]
Thank you for helping out @SpeakingOfBrad! I will close this issue, as the problem seems to be solved already.
