### ISSUE TITLE
[Bug] Issues with the App in a Raspberry pi 5

### ISSUE THREAD

**Issue by joao8545** [MauriceNino/dashdot#939]
### Description of the bug

Hi I just cloned the repo and built the docker image in Raspberry Pi 5 and the container seems to be broken.

### How to reproduce

docker compose up -d                                                                                   
[+] Building 289.8s (9/9) FINISHED                                                                       
 => [dash internal] load build definition from Dockerfile                                                          0.3s
 => => transferring dockerfile: 2.29kB                                                                             0.0s
 => [dash internal] load .dockerignore                                                                             0.3s
 => => transferring context: 303B                                                                                  0.0s
 => [dash internal] load metadata for docker.io/library/node:18-alpine                                             6.1s
 => [dash auth] library/node:pull token for registry-1.docker.io                                                   0.0s
 => [dash base 1/3] FROM docker.io/library/node:18-alpine@sha256:3428c2de886bf4378657da6fe86e105573a609c94df1f7d  34.2s
 => => resolve docker.io/library/node:18-alpine@sha256:3428c2de886bf4378657da6fe86e105573a609c94df1f7d6a70e57d2b5  0.3s
 => => sha256:9eaff0e27201ad0314833288eb33dd65b1952adb3523b850d7526517ad17f3c7 2.34MB / 2.34MB                    11.2s
 => => sha256:3428c2de886bf4378657da6fe86e105573a609c94df1f7d6a70e57d2b51de21f 1.43kB / 1.43kB                     0.0s
 => => sha256:9d25f5814a3f29a229c0a6e75542e6393daed42653878aa3d19292383696c3e5 1.16kB / 1.16kB                     0.0s
 => => sha256:2a0c4196fb4f901a17ca35edc00096d9105187c48a47044e38c150473cf062a8 7.15kB / 7.15kB                     0.0s
 => => sha256:182a74a00cc8ea5ba6570f8b51cc23db25fa284c7a15cbc859fa3eb145fc88f6 40.11MB / 40.11MB                  29.4s
 => => sha256:8e3a7fdfe572d9549c5864cfac97f1a57be85f7069eb87b9977db9aeb3c5fddc 451B / 451B                         0.7s
 => => extracting sha256:182a74a00cc8ea5ba6570f8b51cc23db25fa284c7a15cbc859fa3eb145fc88f6                          3.7s
 => => extracting sha256:9eaff0e27201ad0314833288eb33dd65b1952adb3523b850d7526517ad17f3c7                          0.1s
 => => extracting sha256:8e3a7fdfe572d9549c5864cfac97f1a57be85f7069eb87b9977db9aeb3c5fddc                          0.0s
 => [dash base 2/3] WORKDIR /app                                                                                   3.5s
 => [dash base 3/3] RUN   /bin/echo ">> installing dependencies" &&  apk update &&  apk --no-cache add     lsbl  236.6s
 => [dash dev 1/1] RUN   /bin/echo -e ">> installing dependencies (dev)" &&  apk --no-cache add     git &&  git c  7.1s
 => [dash] exporting to image                                                                                      1.4s
 => => exporting layers                                                                                            1.4s
 => => writing image sha256:563afff98f3fd628960d6739f7b081939da2df45e52b25dc2fcae310abcf6234                       0.0s
 => => naming to docker.io/library/dashdot-dash                                                                    0.0s
[+] Running 2/2
 ✔ Network dashdot_default   Created                                                                               0.1s
 ✔ Container dashdot-dash-1  Created                                                                               1.3s

### Relevant log output

```shell
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```

### Where is your instance running?

Raspberry Pi

**Comment by MauriceNino** [comment]
Hi, there seems to be some information missing for this.

1. What command are you using to build the project?
2. What are your intentions for building the project? (development, or production usage?)
3. What is your architecture?

I will close this for now, because I don't think this is actually a bug, but feel free to post the information above and I will reopen this if there is actually an issue.
