### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by VeloAddict** [MauriceNino/dashdot#941]
### Description of the bug

`docker container run -it   -p 8080:3001   -v /:/mnt/host:ro   --privileged   mauricenino/dashdot`
Does not run. Exits with error.

### Relevant log output

```shell
Status: Downloaded newer image for mauricenino/dashdot:latest
yarn run v1.22.19
$ node .
listening on *:3001
Using default network interface "wlan0"
Using host os version from "/mnt/host/etc/os-release"
TypeError: Cannot read properties of undefined (reading 'replace')
    at /app/dist/apps/server/main.js:11:256944
    at Generator.next (<anonymous>)
    at a (/app/dist/apps/server/main.js:1:3417)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Where is your instance running?

Raspberry Pi

**Comment by eded333** [comment]
> ### Description of the bug
> `docker container run -it -p 8080:3001 -v /:/mnt/host:ro --privileged mauricenino/dashdot` Does not run. Exits with error.
> 
> ### How to reproduce
> _No response_
> 
> ### Relevant log output
> ```shell
> Status: Downloaded newer image for mauricenino/dashdot:latest
> yarn run v1.22.19
> $ node .
> listening on *:3001
> Using default network interface "wlan0"
> Using host os version from "/mnt/host/etc/os-release"
> TypeError: Cannot read properties of undefined (reading 'replace')
>     at /app/dist/apps/server/main.js:11:256944
>     at Generator.next (<anonymous>)
>     at a (/app/dist/apps/server/main.js:1:3417)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> ### Info output of dashdot cli
> _No response_
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### Where is your instance running?
> Raspberry Pi
> 
> ### Additional context
> _No response_

Try the dev version, its working for me.
mauricenino/dashdot:dev

**Comment by rlewis187** [comment]
> > ### Description of the bug
> > `docker container run -it -p 8080:3001 -v /:/mnt/host:ro --privileged mauricenino/dashdot` Does not run. Exits with error.
> > ### How to reproduce
> > _No response_
> > ### Relevant log output
> > ```shell
> > Status: Downloaded newer image for mauricenino/dashdot:latest
> > yarn run v1.22.19
> > $ node .
> > listening on *:3001
> > Using default network interface "wlan0"
> > Using host os version from "/mnt/host/etc/os-release"
> > TypeError: Cannot read properties of undefined (reading 'replace')
> >     at /app/dist/apps/server/main.js:11:256944
> >     at Generator.next (<anonymous>)
> >     at a (/app/dist/apps/server/main.js:1:3417)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > error Command failed with exit code 1.
> > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Info output of dashdot cli
> > _No response_
> > ### What browsers are you seeing the problem on?
> > _No response_
> > ### Where is your instance running?
> > Raspberry Pi
> > ### Additional context
> > _No response_
> 
> Try the dev version, its working for me. mauricenino/dashdot:dev

This worked for meon a raspberry Pi 5 running Bookworm

**Comment by VeloAddict** [comment]
Thanks, but I ended up writing my own API and UI.

**Comment by MauriceNino** [comment]
Hi, this issue should be fixed on the main version now as well. Sorry for the delay.

**Comment by ringuerel** [comment]
@MauriceNino I'm facing same issue on the "from source" installation, using Kamrui miniPC, windows 11.
`Version file not found. This is normal on from-source builds.
listening on *:3001
Acquiring Windows Persistent Powershell
Could not get default iface path
Using default network interface with no modifications
Using host os version from "/etc/os-release"
TypeError: Cannot read properties of undefined (reading 'type')
    at C:\share\dashdot\dist\apps\server\main.js:1:1688116
    at Generator.next (<anonymous>)
    at a (C:\share\dashdot\dist\apps\server\main.js:1:3472)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Releasing Windows Persistent Powershell`
