### ISSUE TITLE
[Bug] Unable to correctly read host's entire storage capacity

### ISSUE THREAD

**Issue by BiFangKNT** [MauriceNino/dashdot#947]
### Description of the bug

First of all, please forgive my poor English. The following are all machine translations:

The system version of my machine is Synology’s ds918+ DSM 7.1.1-42962 Update 6. At the beginning, I followed the documentation tutorial to deploy in docker, but the program could not even read the correct storage usage.

![image](https://github.com/MauriceNino/dashdot/assets/93891533/1b7a95ba-8b4b-411b-8e27-d15d705afafc)

I tried to set `/volume1:/mnt/host/volume1:ro` in the environment variable, so that the storage usage can be displayed correctly, but the complete storage space still cannot be read correctly.

![image](https://github.com/MauriceNino/dashdot/assets/93891533/b380c4c1-69d0-44c4-8d63-c7af7b7f4649)

The drive information shown by info is correct except for the capacity. My two drives "sda" and "sdb" are two 4T Seagate SkyHawk HDDs of the same model, with a total available factory capacity of 6.97T.

![image](https://github.com/MauriceNino/dashdot/assets/93891533/d7a717f1-f0c9-4a1c-9f03-916c7bbd4510)

The drive's capacity reading in the visualization panel is wrong.

![image](https://github.com/MauriceNino/dashdot/assets/93891533/3dc519da-1817-4486-a3f8-3ad856ff72b1)

Also, let me mention that my machine is equipped with Black Synology and uses a 32G USB flash drive as the boot disk to boot the system.

So,is there any way to solve this problem?

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Desktop PC (Linux)

**Comment by BiFangKNT** [comment]
> ### Description of the bug
> First of all, please forgive my poor English. The following are all machine translations:
> 
> The system version of my machine is Synology’s ds918+ DSM 7.1.1-42962 Update 6. At the beginning, I followed the documentation tutorial to deploy in docker, but the program could not even read the correct storage usage.
> 
> ![image](https://private-user-images.githubusercontent.com/93891533/288999476-1b7a95ba-8b4b-411b-8e27-d15d705afafc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjI5ODAsIm5iZiI6MTcwMjAyMjY4MCwicGF0aCI6Ii85Mzg5MTUzMy8yODg5OTk0NzYtMWI3YTk1YmEtOGI0Yi00MTFiLThlMjctZDE1ZDcwNWFmYWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZmUyNGY1YjIyMzUwNDNkMjFmMjBmZmM2YmY2NzVhZGJlMDk4YjUzMTZlOGMxYzRhZDM0ODBmNGUzYjgzNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ldIZ_aZbMnk7GHT8dYqCc7u5SZPOepumKsGbtU_1WuE)
> 
> I tried to set `/volume1:/mnt/host/volume1:ro` in the environment variable, so that the storage usage can be displayed correctly, but the complete storage space still cannot be read correctly.
> 
> ![image](https://private-user-images.githubusercontent.com/93891533/288999080-b380c4c1-69d0-44c4-8d63-c7af7b7f4649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjI5ODAsIm5iZiI6MTcwMjAyMjY4MCwicGF0aCI6Ii85Mzg5MTUzMy8yODg5OTkwODAtYjM4MGM0YzEtNjlkMC00NGM0LThkNjMtYzdhZjdiN2Y0NjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDNhMWU3MGY1NTRmMTJkOTQ5NjgxOGU1MjE3Mjg1YjJhNzc3NjQ2NjRlZjNhYzA4NDJkMzMyNDI5OTVkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OAKA6Rbhp2W4tDagNUndDSgaLguGl972gxxOJZRuqQg)
> 
> The information in the info shows that the Storage is correctly identified.
> 
> ![image](https://private-user-images.githubusercontent.com/93891533/289001376-d7a717f1-f0c9-4a1c-9f03-916c7bbd4510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjI5ODAsIm5iZiI6MTcwMjAyMjY4MCwicGF0aCI6Ii85Mzg5MTUzMy8yODkwMDEzNzYtZDdhNzE3ZjEtZjBjOS00YTFjLTlmMDMtOTE2YzdiYmQ0NTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZTRjNzFjYzJiZDIxYzU1Y2YzM2U5NzY2MzI2YWViY2FmMGFiN2YzMjRkMmI5NzM1YTQ0ZTA1MGZmM2QzZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VnS0zMrtypn_SGOgJS21ieiNKh1WCjOKeRvIS2LorB0)
> 
> However, the drive's capacity reading in the visualization panel is wrong.
> 
> ![image](https://private-user-images.githubusercontent.com/93891533/289002156-3dc519da-1817-4486-a3f8-3ad856ff72b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjI5ODAsIm5iZiI6MTcwMjAyMjY4MCwicGF0aCI6Ii85Mzg5MTUzMy8yODkwMDIxNTYtM2RjNTE5ZGEtMTgxNy00NDg2LWEzZjgtM2FkODU2ZmY3MmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OTk2MWUwODI0NGIxYzI5Yzc1YjZiYTU5Mzc3YTU0OWNiYTUwZDRhNzgyYjBiMTA3Y2U3NzkyN2MxOTMyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyEU1SserLfaGY74-uj7F-kYQN4b-PsHbUR3OXi6Fj4)
> 
> My machine is equipped with Black Synology and uses a 32G USB disk as the boot disk to boot the system, so I suspect that the program recognizes this USB disk as the system space. Is there any way to solve this problem?
> 
> ### How to reproduce
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Info output of dashdot cli
> _No response_
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### Where is your instance running?
> Desktop PC (Linux)
> 
> ### Additional context
> _No response_

Oh no, I mean, the drive information displayed by info is correct, except for the capacity. My two drives "sda" and "sdb" are two 4T Seagate Cool Eagle HDDs of the same model, with a total available factory capacity of 6.97T.

**Comment by MauriceNino** [comment]
Hello there!

Please update the application to the latest version and if that does not fix your issues, try the following command and paste the output in here:

```
docker exec CONTAINER yarn cli raw-data --storage
```

**Comment by MauriceNino** [comment]
Seeing that this is also a Synology specific issue, I would kindly ask you to move all conversation to this task: #938, so we don't have duplicate issues on the board. Thank you!
