### ISSUE TITLE
misspelled memory brand

### ISSUE THREAD

**Issue by cirrusflyer** [MauriceNino/dashdot#977]
### Description of the bug

Under memory, the brand of Crucial is misspelled as "Crutial".

### What browsers are you seeing the problem on?

Chrome

### Where is your instance running?

Raspberry Pi

**Comment by MauriceNino** [comment]
I am just using what your OS is telling me it is called. You can use [this](https://getdashdot.com/docs/config/overrides#dashdot_override_ram_brand) to override the default value.
